// This file is autogenerated: please see the codegen template "Options"
#ifndef PDFTRON_H_CPPPDFWordToPDFOptions
#define PDFTRON_H_CPPPDFWordToPDFOptions

#include <PDF/ConversionOptions.h>

namespace pdftron{ namespace PDF{ 

class WordToPDFOptions: public ConversionOptions
{
public:
	WordToPDFOptions();

	~WordToPDFOptions();



	
	/**
	* Gets the value LayoutResourcesPluginPath from the options object
	* The path at which the pdftron-provided font resource plugin resides
	* @ return a UString, The path at which the pdftron-provided font resource plugin resides.
	*/
	UString GetLayoutResourcesPluginPath();

	/**
	* Sets the value for LayoutResourcesPluginPath in the options object
	* The path at which the pdftron-provided font resource plugin resides
	* @param value: The path at which the pdftron-provided font resource plugin resides
	* @return this object, for call chaining
	*/
	WordToPDFOptions& SetLayoutResourcesPluginPath(UString value);

	
	/**
	* Gets the value ResourceDocPath from the options object
	* The path at which the a .docx resource document resides
	* @ return a UString, The path at which the a .docx resource document resides.
	*/
	UString GetResourceDocPath();

	/**
	* Sets the value for ResourceDocPath in the options object
	* The path at which the a .docx resource document resides
	* @param value: The path at which the a .docx resource document resides
	* @return this object, for call chaining
	*/
	WordToPDFOptions& SetResourceDocPath(UString value);

	
	/**
	* Gets the value SmartSubstitutionPluginPath from the options object
	* The path at which the pdftron-provided font resource plugin resides
	* @ return a UString, The path at which the pdftron-provided font resource plugin resides.
	*/
	UString GetSmartSubstitutionPluginPath();

	/**
	* Sets the value for SmartSubstitutionPluginPath in the options object
	* The path at which the pdftron-provided font resource plugin resides
	* @param value: The path at which the pdftron-provided font resource plugin resides
	* @return this object, for call chaining
	*/
	WordToPDFOptions& SetSmartSubstitutionPluginPath(UString value);

};

}
}

#include "../Impl/WordToPDFOptions.inl"
#endif // PDFTRON_H_CPPPDFWordToPDFOptions
