//---------------------------------------------------------------------------------------
// Copyright (c) 2001-2021 by PDFTron Systems Inc. All Rights Reserved.
// Consult legal.txt regarding legal and license information.
//---------------------------------------------------------------------------------------

#ifndef COMPATIBILITYALIAS_H
#define COMPATIBILITYALIAS_H

#define ReferencePos PTReferencePos
#define e_begin e_ptbegin
#define e_end e_ptend
#define e_cur e_ptcur
#define AnnotationOutputFlag PTAnnotationOutputFlag
#define e_internal_xfdf e_ptinternal_xfdf
#define e_external_xfdf e_ptexternal_xfdf
#define e_flatten e_ptflatten
#define ProxyType PTProxyType
#define e_p_default e_ptp_default
#define e_p_none e_ptp_none
#define e_http e_pthttp
#define e_socks5 e_ptsocks5
#define ErrorHandling PTErrorHandling
#define e_abort e_ptabort
#define e_skip e_ptskip
#define e_ignore e_ptignore
#define CompressionMode PTCompressionMode
#define e_retain e_ptretain
#define e_flate e_ptflate
#define e_jpeg e_ptjpeg
#define e_jpeg2000 e_ptjpeg2000
#define e_none e_ptnone
#define DownsampleMode PTDownsampleMode
#define e_off e_ptoff
#define e_ds_default e_ptds_default
#define MonoCompressionMode PTMonoCompressionMode
#define e_mn_jbig2 e_ptmn_jbig2
#define e_mn_flate e_ptmn_flate
#define e_mn_none e_ptmn_none
#define MonoDownsampleMode PTMonoDownsampleMode
#define e_mn_off e_ptmn_off
#define e_mn_default e_ptmn_default
#define BdStyle PTBdStyle
#define e_solid e_ptsolid
#define e_dashed e_ptdashed
#define e_beveled e_ptbeveled
#define e_inset e_ptinset
#define e_underline e_ptunderline
#define SaveOptions PTSaveOptions
#define e_incremental e_ptincremental
#define e_remove_unused e_ptremove_unused
#define e_hex_strings e_pthex_strings
#define e_omit_xref e_ptomit_xref
#define e_linearized e_ptlinearized
#define e_compatibility e_ptcompatibility
#define ObjType PTObjType
#define e_null e_ptnull
#define e_bool e_ptbool
#define e_number e_ptnumber
#define e_name e_ptname
#define e_string e_ptstring
#define e_dict e_ptdict
#define e_array e_ptarray
#define e_stream e_ptstream
#define Permission PTPermission
#define e_owner e_ptowner
#define e_doc_open e_ptdoc_open
#define e_doc_modify e_ptdoc_modify
#define e_print e_ptprint
#define e_print_high e_ptprint_high
#define e_extract_content e_ptextract_content
#define e_mod_annot e_ptmod_annot
#define e_fill_forms e_ptfill_forms
#define e_access_support e_ptaccess_support
#define e_assemble_doc e_ptassemble_doc
#define AlgorithmType PTAlgorithmType
#define e_RC4_40 e_ptRC4_40
#define e_RC4_128 e_ptRC4_128
#define e_AES e_ptAES
#define OverloadedFunction PTOverloadedFunction
#define has_CloneProc pthas_CloneProc
#define has_AuthProc pthas_AuthProc
#define has_AuthFailedProc pthas_AuthFailedProc
#define has_GetAuthDataProc pthas_GetAuthDataProc
#define has_EditSecurDataProc pthas_EditSecurDataProc
#define has_FillEncDictProc pthas_FillEncDictProc
#define FunctionType PTFunctionType
#define e_sampled e_ptsampled
#define e_exponential e_ptexponential
#define e_stitching e_ptstitching
#define e_postscript e_ptpostscript
#define ColorSpaceType PTColorSpaceType
#define e_device_gray e_ptdevice_gray
#define e_device_rgb e_ptdevice_rgb
#define e_device_cmyk e_ptdevice_cmyk
#define e_cal_gray e_ptcal_gray
#define e_cal_rgb e_ptcal_rgb
#define e_lab e_ptlab
#define e_icc e_pticc
#define e_indexed e_ptindexed
#define e_pattern e_ptpattern
#define e_separation e_ptseparation
#define e_device_n e_ptdevice_n
#define e_c_null e_ptc_null
#define Box PTBox
#define e_media e_ptmedia
#define e_crop e_ptcrop
#define e_bleed e_ptbleed
#define e_trim e_pttrim
#define e_art e_ptart
#define Rotate PTRotate
#define e_0 e_pt0
#define e_90 e_pt90
#define e_180 e_pt180
#define e_270 e_pt270
#define GStateAttribute PTGStateAttribute
#define e_transform e_pttransform
#define e_rendering_intent e_ptrendering_intent
#define e_stroke_cs e_ptstroke_cs
#define e_stroke_color e_ptstroke_color
#define e_fill_cs e_ptfill_cs
#define e_fill_color e_ptfill_color
#define e_line_width e_ptline_width
#define e_line_cap e_ptline_cap
#define e_line_join e_ptline_join
#define e_flatness e_ptflatness
#define e_miter_limit e_ptmiter_limit
#define e_dash_pattern e_ptdash_pattern
#define e_char_spacing e_ptchar_spacing
#define e_word_spacing e_ptword_spacing
#define e_horizontal_scale e_pthorizontal_scale
#define e_leading e_ptleading
#define e_font e_ptfont
#define e_font_size e_ptfont_size
#define e_text_render_mode e_pttext_render_mode
#define e_text_rise e_pttext_rise
#define e_text_knockout e_pttext_knockout
#define e_text_pos_offset e_pttext_pos_offset
#define e_blend_mode e_ptblend_mode
#define e_opacity_fill e_ptopacity_fill
#define e_opacity_stroke e_ptopacity_stroke
#define e_alpha_is_shape e_ptalpha_is_shape
#define e_soft_mask e_ptsoft_mask
#define e_smoothnes e_ptsmoothnes
#define e_auto_stoke_adjust e_ptauto_stoke_adjust
#define e_stroke_overprint e_ptstroke_overprint
#define e_fill_overprint e_ptfill_overprint
#define e_overprint_mode e_ptoverprint_mode
#define e_transfer_funct e_pttransfer_funct
#define e_BG_funct e_ptBG_funct
#define e_UCR_funct e_ptUCR_funct
#define e_halftone e_pthalftone
#define e_g_null e_ptg_null
#define LineCap PTLineCap
#define e_butt_cap e_ptbutt_cap
#define e_round_cap e_ptround_cap
#define e_square_cap e_ptsquare_cap
#define LineJoin PTLineJoin
#define e_miter_join e_ptmiter_join
#define e_round_join e_ptround_join
#define e_bevel_join e_ptbevel_join
#define TextRenderingMode PTTextRenderingMode
#define e_fill_text e_ptfill_text
#define e_stroke_text e_ptstroke_text
#define e_fill_stroke_text e_ptfill_stroke_text
#define e_invisible_text e_ptinvisible_text
#define e_fill_clip_text e_ptfill_clip_text
#define e_stroke_clip_text e_ptstroke_clip_text
#define e_fill_stroke_clip_text e_ptfill_stroke_clip_text
#define e_clip_text e_ptclip_text
#define RenderingIntent PTRenderingIntent
#define e_absolute_colorimetric e_ptabsolute_colorimetric
#define e_relative_colorimetric e_ptrelative_colorimetric
#define e_saturation e_ptsaturation
#define e_perceptual e_ptperceptual
#define BlendMode PTBlendMode
#define e_bl_compatible e_ptbl_compatible
#define e_bl_normal e_ptbl_normal
#define e_bl_multiply e_ptbl_multiply
#define e_bl_screen e_ptbl_screen
#define e_bl_difference e_ptbl_difference
#define e_bl_darken e_ptbl_darken
#define e_bl_lighten e_ptbl_lighten
#define e_bl_color_dodge e_ptbl_color_dodge
#define e_bl_color_burn e_ptbl_color_burn
#define e_bl_exclusion e_ptbl_exclusion
#define e_bl_hard_light e_ptbl_hard_light
#define e_bl_overlay e_ptbl_overlay
#define e_bl_soft_light e_ptbl_soft_light
#define e_bl_luminosity e_ptbl_luminosity
#define e_bl_hue e_ptbl_hue
#define e_bl_saturation e_ptbl_saturation
#define e_bl_color e_ptbl_color
#define FieldType PTFieldType
#define e_button e_ptbutton
#define e_check e_ptcheck
#define e_radio e_ptradio
#define e_text e_pttext
#define e_choice e_ptchoice
#define e_signature e_ptsignature
#define e_f_null e_ptf_null
#define FieldFlag PTFieldFlag
#define e_read_only e_ptread_only
#define e_required e_ptrequired
#define e_no_export e_ptno_export
#define e_pushbutton_flag e_ptpushbutton_flag
#define e_radio_flag e_ptradio_flag
#define e_toggle_to_off e_pttoggle_to_off
#define e_radios_in_unison e_ptradios_in_unison
#define e_multiline e_ptmultiline
#define e_password e_ptpassword
#define e_file_select e_ptfile_select
#define e_no_spellcheck e_ptno_spellcheck
#define e_no_scroll e_ptno_scroll
#define e_comb e_ptcomb
#define e_rich_text e_ptrich_text
#define e_combo e_ptcombo
#define e_edit e_ptedit
#define e_sort e_ptsort
#define e_multiselect e_ptmultiselect
#define e_commit_on_sel_change e_ptcommit_on_sel_change
#define TextJustification PTTextJustification
#define e_left_justified e_ptleft_justified
#define e_centered e_ptcentered
#define e_right_justified e_ptright_justified
#define AnnotType PTAnnotType
#define e_Text e_ptText
#define e_Link e_ptLink
#define e_FreeText e_ptFreeText
#define e_Line e_ptLine
#define e_Square e_ptSquare
#define e_Circle e_ptCircle
#define e_Polygon e_ptPolygon
#define e_Polyline e_ptPolyline
#define e_Highlight e_ptHighlight
#define e_Underline e_ptUnderline
#define e_Squiggly e_ptSquiggly
#define e_StrikeOut e_ptStrikeOut
#define e_Stamp e_ptStamp
#define e_Caret e_ptCaret
#define e_Ink e_ptInk
#define e_Popup e_ptPopup
#define e_FileAttachment e_ptFileAttachment
#define e_Sound e_ptSound
#define e_Movie e_ptMovie
#define e_Widget e_ptWidget
#define e_Screen e_ptScreen
#define e_PrinterMark e_ptPrinterMark
#define e_TrapNet e_ptTrapNet
#define e_Watermark e_ptWatermark
#define e_3D e_pt3D
#define e_Redact e_ptRedact
#define e_Projection e_ptProjection
#define e_RichMedia e_ptRichMedia
#define e_Unknown e_ptUnknown
#define AnnotFlag PTAnnotFlag
#define e_invisible e_ptinvisible
#define e_hidden e_pthidden
#define e_print_annot e_ptprint_annot
#define e_no_zoom e_ptno_zoom
#define e_no_rotate e_ptno_rotate
#define e_no_view e_ptno_view
#define e_annot_read_only e_ptannot_read_only
#define e_locked e_ptlocked
#define e_toggle_no_view e_pttoggle_no_view
#define e_locked_contents e_ptlocked_contents
#define AnnotationState PTAnnotationState
#define e_normal e_ptnormal
#define e_rollover e_ptrollover
#define e_down e_ptdown
#define BorderEffect PTBorderEffect
#define e_None e_ptNone
#define e_Cloudy e_ptCloudy
#define FileIcon PTFileIcon
#define e_Graph e_ptGraph
#define e_PushPin e_ptPushPin
#define e_Paperclip e_ptPaperclip
#define e_Tag e_ptTag
#define e_fi_Unknown e_ptfi_Unknown
#define FitType PTFitType
#define e_XYZ e_ptXYZ
#define e_Fit e_ptFit
#define e_FitH e_ptFitH
#define e_FitV e_ptFitV
#define e_FitR e_ptFitR
#define e_FitB e_ptFitB
#define e_FitBH e_ptFitBH
#define e_FitBV e_ptFitBV
#define ActionType PTActionType
#define e_GoTo e_ptGoTo
#define e_GoToR e_ptGoToR
#define e_GoToE e_ptGoToE
#define e_Launch e_ptLaunch
#define e_Thread e_ptThread
#define e_URI e_ptURI
#define e_a_sound e_pta_sound
#define e_a_Movie e_pta_Movie
#define e_Hide e_ptHide
#define e_Named e_ptNamed
#define e_SubmitForm e_ptSubmitForm
#define e_ResetForm e_ptResetForm
#define e_ImportData e_ptImportData
#define e_JavaScript e_ptJavaScript
#define e_SetOCGState e_ptSetOCGState
#define e_Rendition e_ptRendition
#define e_Trans e_ptTrans
#define e_GoTo3DView e_ptGoTo3DView
#define e_RichMediaExecute e_ptRichMediaExecute
#define e_a_Unknown e_pta_Unknown
#define FormActionFlag PTFormActionFlag
#define e_exclude e_ptexclude
#define e_include_no_value_fields e_ptinclude_no_value_fields
#define e_export_format e_ptexport_format
#define e_get_method e_ptget_method
#define e_submit_coordinates e_ptsubmit_coordinates
#define e_xfdf e_ptxfdf
#define e_include_append_saves e_ptinclude_append_saves
#define e_include_annotations e_ptinclude_annotations
#define e_submit_pdf e_ptsubmit_pdf
#define e_canonical_format e_ptcanonical_format
#define e_excl_non_user_annots e_ptexcl_non_user_annots
#define e_excl_F_key e_ptexcl_F_key
#define e_embed_form e_ptembed_form
#define EndingStyle PTEndingStyle
#define e_l_Square e_ptl_Square
#define e_l_Circle e_ptl_Circle
#define e_Diamond e_ptDiamond
#define e_OpenArrow e_ptOpenArrow
#define e_ClosedArrow e_ptClosedArrow
#define e_Butt e_ptButt
#define e_ROpenArrow e_ptROpenArrow
#define e_RClosedArrow e_ptRClosedArrow
#define e_Slash e_ptSlash
#define e_l_None e_ptl_None
#define e_l_Unknown e_ptl_Unknown
#define LineIntentType PTLineIntentType
#define e_LineArrow e_ptLineArrow
#define e_LineDimension e_ptLineDimension
#define e_l_null e_ptl_null
#define CapPos PTCapPos
#define e_Inline e_ptInline
#define e_Top e_ptTop
#define IntentName PTIntentName
#define e_f_FreeText e_ptf_FreeText
#define e_FreeTextCallout e_ptFreeTextCallout
#define e_FreeTextTypeWriter e_ptFreeTextTypeWriter
#define e_f_Unknown e_ptf_Unknown
#define LinkHighlightingMode PTLinkHighlightingMode
#define e_l_none e_ptl_none
#define e_invert e_ptinvert
#define e_highlight_outline e_pthighlight_outline
#define e_push e_ptpush
#define PolyLineIntentType PTPolyLineIntentType
#define e_PolygonCloud e_ptPolygonCloud
#define e_PolyLineDimension e_ptPolyLineDimension
#define e_PolygonDimension e_ptPolygonDimension
#define e_p_Unknown e_ptp_Unknown
#define QuadForm PTQuadForm
#define e_LeftJustified e_ptLeftJustified
#define e_Centered e_ptCentered
#define e_RightJustified e_ptRightJustified
#define e_r_None e_ptr_None
#define RubberStampIcon PTRubberStampIcon
#define e_Approved e_ptApproved
#define e_Experimental e_ptExperimental
#define e_NotApproved e_ptNotApproved
#define e_AsIs e_ptAsIs
#define e_Expired e_ptExpired
#define e_NotForPublicRelease e_ptNotForPublicRelease
#define e_Confidential e_ptConfidential
#define e_Final e_ptFinal
#define e_Sold e_ptSold
#define e_Departmental e_ptDepartmental
#define e_ForComment e_ptForComment
#define e_TopSecret e_ptTopSecret
#define e_ForPublicRelease e_ptForPublicRelease
#define e_Draft e_ptDraft
#define e_r_Unknown e_ptr_Unknown
#define ScreenIconCaptionRelation PTScreenIconCaptionRelation
#define e_NoIcon e_ptNoIcon
#define e_NoCaption e_ptNoCaption
#define e_CBelowI e_ptCBelowI
#define e_CAboveI e_ptCAboveI
#define e_CRightILeft e_ptCRightILeft
#define e_CLeftIRight e_ptCLeftIRight
#define e_COverlayI e_ptCOverlayI
#define ScreenScaleCondition PTScreenScaleCondition
#define e_Always e_ptAlways
#define e_WhenBigger e_ptWhenBigger
#define e_WhenSmaller e_ptWhenSmaller
#define e_Never e_ptNever
#define ScreenScaleType PTScreenScaleType
#define e_Anamorphic e_ptAnamorphic
#define e_Proportional e_ptProportional
#define SoundIcon PTSoundIcon
#define e_Speaker e_ptSpeaker
#define e_Mic e_ptMic
#define e_s_Unknown e_pts_Unknown
#define TextIcon PTTextIcon
#define e_Comment e_ptComment
#define e_Key e_ptKey
#define e_Help e_ptHelp
#define e_NewParagraph e_ptNewParagraph
#define e_Paragraph e_ptParagraph
#define e_Insert e_ptInsert
#define e_Note e_ptNote
#define e_t_Unknown e_ptt_Unknown
#define WidgetHighlightingMode PTWidgetHighlightingMode
#define e_w_none e_ptw_none
#define e_w_invert e_ptw_invert
#define e_w_outline e_ptw_outline
#define e_w_push e_ptw_push
#define e_toggle e_pttoggle
#define WidgetIconCaptionRelation PTWidgetIconCaptionRelation
#define e_w_NoIcon e_ptw_NoIcon
#define e_w_NoCaption e_ptw_NoCaption
#define e_w_CBelowI e_ptw_CBelowI
#define e_w_CAboveI e_ptw_CAboveI
#define e_w_CRightILeft e_ptw_CRightILeft
#define e_w_CLeftIRight e_ptw_CLeftIRight
#define e_w_COverlayI e_ptw_COverlayI
#define WidgetScaleCondition PTWidgetScaleCondition
#define e_w_Always e_ptw_Always
#define e_w_WhenBigger e_ptw_WhenBigger
#define e_w_WhenSmaller e_ptw_WhenSmaller
#define e_w_Never e_ptw_Never
#define WidgetScaleType PTWidgetScaleType
#define e_w_Anamorphic e_ptw_Anamorphic
#define e_w_Proportional e_ptw_Proportional
#define OCDrawMode PTOCDrawMode
#define e_VisibleOC e_ptVisibleOC
#define e_AllOC e_ptAllOC
#define e_NoOC e_ptNoOC
#define VisibilityPolicyType PTVisibilityPolicyType
#define e_AllOn e_ptAllOn
#define e_AnyOn e_ptAnyOn
#define e_AnyOff e_ptAnyOff
#define e_AllOff e_ptAllOff
#define Conformance PTConformance
#define e_NoConformance e_ptNoConformance
#define e_Level1A e_ptLevel1A
#define e_Level1B e_ptLevel1B
#define e_Level2A e_ptLevel2A
#define e_Level2B e_ptLevel2B
#define e_Level2U e_ptLevel2U
#define e_Level3A e_ptLevel3A
#define e_Level3B e_ptLevel3B
#define e_Level3U e_ptLevel3U
#define ErrorCode PTErrorCode
#define e_PDFA0_1_0 e_ptPDFA0_1_0
#define e_PDFA0_1_1 e_ptPDFA0_1_1
#define e_PDFA0_1_2 e_ptPDFA0_1_2
#define e_PDFA0_1_3 e_ptPDFA0_1_3
#define e_PDFA0_1_4 e_ptPDFA0_1_4
#define e_PDFA0_1_5 e_ptPDFA0_1_5
#define e_PDFA1_2_1 e_ptPDFA1_2_1
#define e_PDFA1_2_2 e_ptPDFA1_2_2
#define e_PDFA1_3_1 e_ptPDFA1_3_1
#define e_PDFA1_3_2 e_ptPDFA1_3_2
#define e_PDFA1_3_3 e_ptPDFA1_3_3
#define e_PDFA1_3_4 e_ptPDFA1_3_4
#define e_PDFA1_4_1 e_ptPDFA1_4_1
#define e_PDFA1_4_2 e_ptPDFA1_4_2
#define e_PDFA1_6_1 e_ptPDFA1_6_1
#define e_PDFA1_7_1 e_ptPDFA1_7_1
#define e_PDFA1_7_2 e_ptPDFA1_7_2
#define e_PDFA1_7_3 e_ptPDFA1_7_3
#define e_PDFA1_7_4 e_ptPDFA1_7_4
#define e_PDFA1_8_1 e_ptPDFA1_8_1
#define e_PDFA1_8_2 e_ptPDFA1_8_2
#define e_PDFA1_8_3 e_ptPDFA1_8_3
#define e_PDFA1_8_4 e_ptPDFA1_8_4
#define e_PDFA1_8_5 e_ptPDFA1_8_5
#define e_PDFA1_8_6 e_ptPDFA1_8_6
#define e_PDFA1_10_1 e_ptPDFA1_10_1
#define e_PDFA1_11_1 e_ptPDFA1_11_1
#define e_PDFA1_11_2 e_ptPDFA1_11_2
#define e_PDFA1_12_1 e_ptPDFA1_12_1
#define e_PDFA1_12_2 e_ptPDFA1_12_2
#define e_PDFA1_12_3 e_ptPDFA1_12_3
#define e_PDFA1_12_4 e_ptPDFA1_12_4
#define e_PDFA1_12_5 e_ptPDFA1_12_5
#define e_PDFA1_12_6 e_ptPDFA1_12_6
#define e_PDFA1_13_1 e_ptPDFA1_13_1
#define e_PDFA2_2_1 e_ptPDFA2_2_1
#define e_PDFA2_3_2 e_ptPDFA2_3_2
#define e_PDFA2_3_3 e_ptPDFA2_3_3
#define e_PDFA2_3_3_1 e_ptPDFA2_3_3_1
#define e_PDFA2_3_3_2 e_ptPDFA2_3_3_2
#define e_PDFA2_3_4_1 e_ptPDFA2_3_4_1
#define e_PDFA2_4_1 e_ptPDFA2_4_1
#define e_PDFA2_4_2 e_ptPDFA2_4_2
#define e_PDFA2_4_3 e_ptPDFA2_4_3
#define e_PDFA2_4_4 e_ptPDFA2_4_4
#define e_PDFA2_5_1 e_ptPDFA2_5_1
#define e_PDFA2_5_2 e_ptPDFA2_5_2
#define e_PDFA2_6_1 e_ptPDFA2_6_1
#define e_PDFA2_7_1 e_ptPDFA2_7_1
#define e_PDFA2_8_1 e_ptPDFA2_8_1
#define e_PDFA2_9_1 e_ptPDFA2_9_1
#define e_PDFA2_10_1 e_ptPDFA2_10_1
#define e_PDFA3_2_1 e_ptPDFA3_2_1
#define e_PDFA3_3_1 e_ptPDFA3_3_1
#define e_PDFA3_3_2 e_ptPDFA3_3_2
#define e_PDFA3_3_3_1 e_ptPDFA3_3_3_1
#define e_PDFA3_3_3_2 e_ptPDFA3_3_3_2
#define e_PDFA3_4_1 e_ptPDFA3_4_1
#define e_PDFA3_5_1 e_ptPDFA3_5_1
#define e_PDFA3_5_2 e_ptPDFA3_5_2
#define e_PDFA3_5_3 e_ptPDFA3_5_3
#define e_PDFA3_5_4 e_ptPDFA3_5_4
#define e_PDFA3_5_5 e_ptPDFA3_5_5
#define e_PDFA3_5_6 e_ptPDFA3_5_6
#define e_PDFA3_6_1 e_ptPDFA3_6_1
#define e_PDFA3_7_1 e_ptPDFA3_7_1
#define e_PDFA3_7_2 e_ptPDFA3_7_2
#define e_PDFA3_7_3 e_ptPDFA3_7_3
#define e_PDFA4_1 e_ptPDFA4_1
#define e_PDFA4_2 e_ptPDFA4_2
#define e_PDFA4_3 e_ptPDFA4_3
#define e_PDFA4_4 e_ptPDFA4_4
#define e_PDFA4_5 e_ptPDFA4_5
#define e_PDFA4_6 e_ptPDFA4_6
#define e_PDFA5_2_1 e_ptPDFA5_2_1
#define e_PDFA5_2_2 e_ptPDFA5_2_2
#define e_PDFA5_2_3 e_ptPDFA5_2_3
#define e_PDFA5_2_4 e_ptPDFA5_2_4
#define e_PDFA5_2_5 e_ptPDFA5_2_5
#define e_PDFA5_2_6 e_ptPDFA5_2_6
#define e_PDFA5_2_7 e_ptPDFA5_2_7
#define e_PDFA5_2_8 e_ptPDFA5_2_8
#define e_PDFA5_2_9 e_ptPDFA5_2_9
#define e_PDFA5_2_10 e_ptPDFA5_2_10
#define e_PDFA5_2_11 e_ptPDFA5_2_11
#define e_PDFA5_3_1 e_ptPDFA5_3_1
#define e_PDFA5_3_2_1 e_ptPDFA5_3_2_1
#define e_PDFA5_3_2_2 e_ptPDFA5_3_2_2
#define e_PDFA5_3_2_3 e_ptPDFA5_3_2_3
#define e_PDFA5_3_2_4 e_ptPDFA5_3_2_4
#define e_PDFA5_3_2_5 e_ptPDFA5_3_2_5
#define e_PDFA5_3_3_1 e_ptPDFA5_3_3_1
#define e_PDFA5_3_3_2 e_ptPDFA5_3_3_2
#define e_PDFA5_3_3_3 e_ptPDFA5_3_3_3
#define e_PDFA5_3_3_4 e_ptPDFA5_3_3_4
#define e_PDFA5_3_4_0 e_ptPDFA5_3_4_0
#define e_PDFA5_3_4_1 e_ptPDFA5_3_4_1
#define e_PDFA5_3_4_2 e_ptPDFA5_3_4_2
#define e_PDFA5_3_4_3 e_ptPDFA5_3_4_3
#define e_PDFA6_1_1 e_ptPDFA6_1_1
#define e_PDFA6_1_2 e_ptPDFA6_1_2
#define e_PDFA6_2_1 e_ptPDFA6_2_1
#define e_PDFA6_2_2 e_ptPDFA6_2_2
#define e_PDFA6_2_3 e_ptPDFA6_2_3
#define e_PDFA7_2_1 e_ptPDFA7_2_1
#define e_PDFA7_2_2 e_ptPDFA7_2_2
#define e_PDFA7_2_3 e_ptPDFA7_2_3
#define e_PDFA7_2_4 e_ptPDFA7_2_4
#define e_PDFA7_2_5 e_ptPDFA7_2_5
#define e_PDFA7_3_1 e_ptPDFA7_3_1
#define e_PDFA7_3_2 e_ptPDFA7_3_2
#define e_PDFA7_3_3 e_ptPDFA7_3_3
#define e_PDFA7_3_4 e_ptPDFA7_3_4
#define e_PDFA7_3_5 e_ptPDFA7_3_5
#define e_PDFA7_3_6 e_ptPDFA7_3_6
#define e_PDFA7_3_7 e_ptPDFA7_3_7
#define e_PDFA7_3_8 e_ptPDFA7_3_8
#define e_PDFA7_3_9 e_ptPDFA7_3_9
#define e_PDFA7_5_1 e_ptPDFA7_5_1
#define e_PDFA7_8_1 e_ptPDFA7_8_1
#define e_PDFA7_8_2 e_ptPDFA7_8_2
#define e_PDFA7_8_3 e_ptPDFA7_8_3
#define e_PDFA7_8_4 e_ptPDFA7_8_4
#define e_PDFA7_8_5 e_ptPDFA7_8_5
#define e_PDFA7_8_6 e_ptPDFA7_8_6
#define e_PDFA7_8_7 e_ptPDFA7_8_7
#define e_PDFA7_8_8 e_ptPDFA7_8_8
#define e_PDFA7_8_9 e_ptPDFA7_8_9
#define e_PDFA7_8_10 e_ptPDFA7_8_10
#define e_PDFA7_8_11 e_ptPDFA7_8_11
#define e_PDFA7_8_12 e_ptPDFA7_8_12
#define e_PDFA7_8_13 e_ptPDFA7_8_13
#define e_PDFA7_8_14 e_ptPDFA7_8_14
#define e_PDFA7_8_15 e_ptPDFA7_8_15
#define e_PDFA7_8_16 e_ptPDFA7_8_16
#define e_PDFA7_8_17 e_ptPDFA7_8_17
#define e_PDFA7_8_18 e_ptPDFA7_8_18
#define e_PDFA7_8_19 e_ptPDFA7_8_19
#define e_PDFA7_8_20 e_ptPDFA7_8_20
#define e_PDFA7_8_21 e_ptPDFA7_8_21
#define e_PDFA7_8_22 e_ptPDFA7_8_22
#define e_PDFA7_8_23 e_ptPDFA7_8_23
#define e_PDFA7_8_24 e_ptPDFA7_8_24
#define e_PDFA7_8_25 e_ptPDFA7_8_25
#define e_PDFA7_8_26 e_ptPDFA7_8_26
#define e_PDFA7_8_27 e_ptPDFA7_8_27
#define e_PDFA7_8_28 e_ptPDFA7_8_28
#define e_PDFA7_8_29 e_ptPDFA7_8_29
#define e_PDFA7_8_30 e_ptPDFA7_8_30
#define e_PDFA7_8_31 e_ptPDFA7_8_31
#define e_PDFA7_11_1 e_ptPDFA7_11_1
#define e_PDFA7_11_2 e_ptPDFA7_11_2
#define e_PDFA7_11_3 e_ptPDFA7_11_3
#define e_PDFA7_11_4 e_ptPDFA7_11_4
#define e_PDFA7_11_5 e_ptPDFA7_11_5
#define e_PDFA9_1 e_ptPDFA9_1
#define e_PDFA9_2 e_ptPDFA9_2
#define e_PDFA9_3 e_ptPDFA9_3
#define e_PDFA9_4 e_ptPDFA9_4
#define e_PDFA3_8_1 e_ptPDFA3_8_1
#define e_PDFA8_2_2 e_ptPDFA8_2_2
#define e_PDFA8_3_3_1 e_ptPDFA8_3_3_1
#define e_PDFA8_3_3_2 e_ptPDFA8_3_3_2
#define e_PDFA8_3_4_1 e_ptPDFA8_3_4_1
#define e_PDFA1_2_3 e_ptPDFA1_2_3
#define e_PDFA1_10_2 e_ptPDFA1_10_2
#define e_PDFA1_10_3 e_ptPDFA1_10_3
#define e_PDFA1_12_10 e_ptPDFA1_12_10
#define e_PDFA1_13_5 e_ptPDFA1_13_5
#define e_PDFA2_3_10 e_ptPDFA2_3_10
#define e_PDFA2_4_2_10 e_ptPDFA2_4_2_10
#define e_PDFA2_4_2_11 e_ptPDFA2_4_2_11
#define e_PDFA2_4_2_12 e_ptPDFA2_4_2_12
#define e_PDFA2_4_2_13 e_ptPDFA2_4_2_13
#define e_PDFA2_5_10 e_ptPDFA2_5_10
#define e_PDFA2_5_11 e_ptPDFA2_5_11
#define e_PDFA2_5_12 e_ptPDFA2_5_12
#define e_PDFA2_8_3_1 e_ptPDFA2_8_3_1
#define e_PDFA2_8_3_2 e_ptPDFA2_8_3_2
#define e_PDFA2_8_3_3 e_ptPDFA2_8_3_3
#define e_PDFA2_8_3_4 e_ptPDFA2_8_3_4
#define e_PDFA2_8_3_5 e_ptPDFA2_8_3_5
#define e_PDFA2_10_20 e_ptPDFA2_10_20
#define e_PDFA2_10_21 e_ptPDFA2_10_21
#define e_PDFA11_0_0 e_ptPDFA11_0_0
#define e_PDFA6_2_11_8 e_ptPDFA6_2_11_8
#define e_PDFA8_1 e_ptPDFA8_1
#define e_PDFA_3E1 e_ptPDFA_3E1
#define e_PDFA_3E2 e_ptPDFA_3E2
#define e_PDFA_3E3 e_ptPDFA_3E3
#define e_PDFA_LAST e_ptPDFA_LAST
#define ContentItemType PTContentItemType
#define e_MCR e_ptMCR
#define e_MCID e_ptMCID
#define e_OBJR e_ptOBJR
#define e_c_Unknown e_ptc_Unknown
#define FlattenThresholdFlag PTFlattenThresholdFlag
#define e_very_strict e_ptvery_strict
#define e_strict e_ptstrict
#define e_default e_ptdefault
#define e_keep_most e_ptkeep_most
#define e_keep_all e_ptkeep_all
#define FlattenFlag PTFlattenFlag
#define e_flatten_off e_ptflatten_off
#define e_flatten_simple e_ptflatten_simple
#define e_flatten_fast e_ptflatten_fast
#define PathSegmentType PTPathSegmentType
#define e_moveto e_ptmoveto
#define e_lineto e_ptlineto
#define e_cubicto e_ptcubicto
#define e_conicto e_ptconicto
#define e_rect e_ptrect
#define e_closepath e_ptclosepath
#define StandardType1Font PTStandardType1Font
#define e_times_roman e_pttimes_roman
#define e_times_bold e_pttimes_bold
#define e_times_italic e_pttimes_italic
#define e_times_bold_italic e_pttimes_bold_italic
#define e_helvetica e_pthelvetica
#define e_helvetica_bold e_pthelvetica_bold
#define e_helvetica_oblique e_pthelvetica_oblique
#define e_helvetica_bold_oblique e_pthelvetica_bold_oblique
#define e_courier e_ptcourier
#define e_courier_bold e_ptcourier_bold
#define e_courier_oblique e_ptcourier_oblique
#define e_courier_bold_oblique e_ptcourier_bold_oblique
#define e_symbol e_ptsymbol
#define e_zapf_dingbats e_ptzapf_dingbats
#define e_ft_null e_ptft_null
#define Encoding PTEncoding
#define e_IdentityH e_ptIdentityH
#define e_Indices e_ptIndices
#define FontType PTFontType
#define e_Type1 e_ptType1
#define e_TrueType e_ptTrueType
#define e_MMType1 e_ptMMType1
#define e_Type3 e_ptType3
#define e_Type0 e_ptType0
#define e_CIDType0 e_ptCIDType0
#define e_CIDType2 e_ptCIDType2
#define ShadingType PTShadingType
#define e_function_shading e_ptfunction_shading
#define e_axial_shading e_ptaxial_shading
#define e_radial_shading e_ptradial_shading
#define e_free_gouraud_shading e_ptfree_gouraud_shading
#define e_lattice_gouraud_shading e_ptlattice_gouraud_shading
#define e_coons_shading e_ptcoons_shading
#define e_tensor_shading e_pttensor_shading
#define e_s_null e_pts_null
#define PatternColorType PTPatternColorType
#define e_uncolored_tiling_pattern e_ptuncolored_tiling_pattern
#define e_colored_tiling_pattern e_ptcolored_tiling_pattern
#define e_shading e_ptshading
#define e_p_null e_ptp_null
#define TilingType PTTilingType
#define e_constant_spacing e_ptconstant_spacing
#define e_no_distortion e_ptno_distortion
#define e_constant_spacing_fast_fill e_ptconstant_spacing_fast_fill
#define InputFilter PTInputFilter
#define e_i_none e_pti_none
#define e_i_jpeg e_pti_jpeg
#define e_jp2 e_ptjp2
#define e_i_flate e_pti_flate
#define e_g3 e_ptg3
#define e_g4 e_ptg4
#define e_ascii_hex e_ptascii_hex
#define ElementType PTElementType
#define e_e_null e_pte_null
#define e_path e_ptpath
#define e_text_begin e_pttext_begin
#define e_text_obj e_pttext_obj
#define e_text_new_line e_pttext_new_line
#define e_text_end e_pttext_end
#define e_image e_ptimage
#define e_inline_image e_ptinline_image
#define e_e_shading e_pte_shading
#define e_form e_ptform
#define e_group_begin e_ptgroup_begin
#define e_group_end e_ptgroup_end
#define e_marked_content_begin e_ptmarked_content_begin
#define e_marked_content_end e_ptmarked_content_end
#define e_marked_content_point e_ptmarked_content_point
#define WriteMode PTWriteMode
#define e_underlay e_ptunderlay
#define e_overlay e_ptoverlay
#define e_replacement e_ptreplacement
#define Threshold PTThreshold
#define e_threshold_very_strict e_ptthreshold_very_strict
#define e_threshold_strict e_ptthreshold_strict
#define e_threshold_default e_ptthreshold_default
#define e_threshold_keep_most e_ptthreshold_keep_most
#define e_threshold_keep_all e_ptthreshold_keep_all
#define FlattenMode PTFlattenMode
#define e_simple e_ptsimple
#define e_fast e_ptfast
#define PageLabelStyle PTPageLabelStyle
#define e_decimal e_ptdecimal
#define e_roman_uppercase e_ptroman_uppercase
#define e_roman_lowercase e_ptroman_lowercase
#define e_alphabetic_uppercase e_ptalphabetic_uppercase
#define e_alphabetic_lowercase e_ptalphabetic_lowercase
#define e_pg_none e_ptpg_none
#define PageSetFilter PTPageSetFilter
#define e_all e_ptall
#define e_even e_pteven
#define e_odd e_ptodd
#define PageMode PTPageMode
#define e_UseNone e_ptUseNone
#define e_UseThumbs e_ptUseThumbs
#define e_UseBookmarks e_ptUseBookmarks
#define e_FullScreen e_ptFullScreen
#define e_UseOC e_ptUseOC
#define e_UseAttachments e_ptUseAttachments
#define PageLayout PTPageLayout
#define e_Default e_ptDefault
#define e_SinglePage e_ptSinglePage
#define e_OneColumn e_ptOneColumn
#define e_TwoColumnLeft e_ptTwoColumnLeft
#define e_TwoColumnRight e_ptTwoColumnRight
#define e_TwoPageLeft e_ptTwoPageLeft
#define e_TwoPageRight e_ptTwoPageRight
#define ViewerPref PTViewerPref
#define e_HideToolbar e_ptHideToolbar
#define e_HideMenubar e_ptHideMenubar
#define e_HideWindowUI e_ptHideWindowUI
#define e_FitWindow e_ptFitWindow
#define e_CenterWindow e_ptCenterWindow
#define e_DisplayDocTitle e_ptDisplayDocTitle
#define InsertFlag PTInsertFlag
#define e_insert_bookmark e_ptinsert_bookmark
#define ExtractFlag PTExtractFlag
#define e_forms_only e_ptforms_only
#define e_annots_only e_ptannots_only
#define e_both e_ptboth
#define e_downloadedtype_page e_ptdownloadedtype_page
#define e_downloadedtype_thumb e_ptdownloadedtype_thumb
#define e_downloadedtype_named_dests e_ptdownloadedtype_named_dests
#define e_downloadedtype_outline e_ptdownloadedtype_outline
#define e_downloadedtype_finished e_ptdownloadedtype_finished
#define e_downloadedtype_failed e_ptdownloadedtype_failed
#define e_downloadedtype_opened e_ptdownloadedtype_opened
#define RasterizerType PTRasterizerType
#define e_BuiltIn e_ptBuiltIn
#define e_GDIPlus e_ptGDIPlus
#define OverprintPreviewMode PTOverprintPreviewMode
#define e_op_off e_ptop_off
#define e_op_on e_ptop_on
#define e_op_pdfx_on e_ptop_pdfx_on
#define PixelFormat PTPixelFormat
#define e_rgba e_ptrgba
#define e_bgra e_ptbgra
#define e_rgb e_ptrgb
#define e_bgr e_ptbgr
#define e_gray e_ptgray
#define e_gray_alpha e_ptgray_alpha
#define e_cmyk e_ptcmyk
#define STATUS_ERR PTSTATUS_ERR
#define STATUS_OK PTSTATUS_OK
#define STATUS_NETWORK_ERR PTSTATUS_NETWORK_ERR
#define STATUS_BAD_CREDENTIALS PTSTATUS_BAD_CREDENTIALS
#define STATUS_SERVICE_DOWN PTSTATUS_SERVICE_DOWN
#define STATUS_INVALID_OPERATION PTSTATUS_INVALID_OPERATION
#define STATUS_NUM PTSTATUS_NUM
#define CMSType PTCMSType
#define e_lcms e_ptlcms
#define e_icm e_pticm
#define e_no_cms e_ptno_cms
#define CharacterOrdering PTCharacterOrdering
#define e_Identity e_ptIdentity
#define e_Japan1 e_ptJapan1
#define e_Japan2 e_ptJapan2
#define e_GB1 e_ptGB1
#define e_CNS1 e_ptCNS1
#define e_Korea1 e_ptKorea1
#define PagePresentationMode PTPagePresentationMode
#define e_single_page e_ptsingle_page
#define e_single_continuous e_ptsingle_continuous
#define e_facing e_ptfacing
#define e_facing_continuous e_ptfacing_continuous
#define e_facing_cover e_ptfacing_cover
#define e_facing_continuous_cover e_ptfacing_continuous_cover
#define TextSelectionMode PTTextSelectionMode
#define e_structural e_ptstructural
#define e_rectangular e_ptrectangular
#define PageViewMode PTPageViewMode
#define e_fit_page e_ptfit_page
#define e_fit_width e_ptfit_width
#define e_fit_height e_ptfit_height
#define e_zoom e_ptzoom
#define PVM_SIZE PTPVM_SIZE
#define SizeType PTSizeType
#define e_relative_scale e_ptrelative_scale
#define e_absolute_size e_ptabsolute_size
#define e_s_font_size e_pts_font_size
#define HorizontalAlignment PTHorizontalAlignment
#define e_horizontal_left e_pthorizontal_left
#define e_horizontal_center e_pthorizontal_center
#define e_horizontal_right e_pthorizontal_right
#define VerticalAlignment PTVerticalAlignment
#define e_vertical_bottom e_ptvertical_bottom
#define e_vertical_center e_ptvertical_center
#define e_vertical_top e_ptvertical_top
#define TextAlignment PTTextAlignment
#define e_align_left e_ptalign_left
#define e_align_center e_ptalign_center
#define e_align_right e_ptalign_right
#define ProcessingFlags PTProcessingFlags
#define e_no_ligature_exp e_ptno_ligature_exp
#define e_no_dup_remove e_ptno_dup_remove
#define e_punct_break e_ptpunct_break
#define e_remove_hidden_text e_ptremove_hidden_text
#define e_no_invisible_text e_ptno_invisible_text
#define XMLOutputFlags PTXMLOutputFlags
#define e_words_as_elements e_ptwords_as_elements
#define e_output_bbox e_ptoutput_bbox
#define e_output_style_info e_ptoutput_style_info
#define TextSearchModes PTTextSearchModes
#define e_reg_expression e_ptreg_expression
#define e_case_sensitive e_ptcase_sensitive
#define e_reg_expression e_ptreg_expression
#define e_whole_word e_ptwhole_word
#define e_case_sensitive e_ptcase_sensitive
#define e_search_up e_ptsearch_up
#define e_whole_word e_ptwhole_word
#define e_page_stop e_ptpage_stop
#define e_search_up e_ptsearch_up
#define e_highlight e_pthighlight
#define e_page_stop e_ptpage_stop
#define e_ambient_string e_ptambient_string
#define e_highlight e_pthighlight
#define e_raw_text_search e_ptraw_text_search

@compatibility_alias Action PTAction;
@compatibility_alias Annot PTAnnot;
@compatibility_alias Appearance PTAppearance;
@compatibility_alias ASCII85Encode PTASCII85Encode;
@compatibility_alias AttrObj PTAttrObj;
@compatibility_alias BitmapInfo PTBitmapInfo;
@compatibility_alias Bookmark PTBookmark;
@compatibility_alias BorderStyle PTBorderStyle;
@compatibility_alias Callback PTCallback;
@compatibility_alias Caret PTCaret;
@compatibility_alias CharIterator PTCharIterator;
@compatibility_alias Circle PTCircle;
@compatibility_alias ClassMap PTClassMap;
@compatibility_alias ColorPt PTColorPt;
@compatibility_alias ColorSpace PTColorSpace;
@compatibility_alias Config PTConfig;
@compatibility_alias ContentItem PTContentItem;
@compatibility_alias ContentReplacer PTContentReplacer;
@compatibility_alias Context PTContext;
@compatibility_alias Convert PTConvert;
@compatibility_alias Date PTDate;
@compatibility_alias Destination PTDestination;
@compatibility_alias DictIterator PTDictIterator;
@compatibility_alias Element PTElement;
@compatibility_alias ElementBuilder PTElementBuilder;
@compatibility_alias ElementReader PTElementReader;
@compatibility_alias ElementWriter PTElementWriter;
@compatibility_alias EPUBOutputOptions PTEPUBOutputOptions;
@compatibility_alias FDFDoc PTFDFDoc;
@compatibility_alias FieldIterator PTFieldIterator;
@compatibility_alias FDFField PTFDFField;
@compatibility_alias FDFFieldIterator PTFDFFieldIterator;
@compatibility_alias FileAttachment PTFileAttachment;
@compatibility_alias FileSpec PTFileSpec;
@compatibility_alias Filter PTFilter;
@compatibility_alias FilterReader PTFilterReader;
@compatibility_alias FilterWriter PTFilterWriter;
@compatibility_alias FlateEncode PTFlateEncode;
@compatibility_alias Flattener PTFlattener;
@compatibility_alias Font PTFont;
@compatibility_alias FreeText PTFreeText;
@compatibility_alias Function PTFunction;
@compatibility_alias Group PTGroup;
@compatibility_alias GSChangesIterator PTGSChangesIterator;
@compatibility_alias GState PTGState;
@compatibility_alias Highlight PTHighlight;
@compatibility_alias HighlightAnnot PTHighlightAnnot;
@compatibility_alias Highlights PTHighlights;
@compatibility_alias HTML2PDF PTHTML2PDF;
@compatibility_alias HTMLOutputOptions PTHTMLOutputOptions;
@compatibility_alias WordOutputOptions PTWordOutputOptions;
@compatibility_alias HTTPRequestOptions PTHTTPRequestOptions;
@compatibility_alias Image PTImage;
@compatibility_alias Image2RGB PTImage2RGB;
@compatibility_alias Image2RGBA PTImage2RGBA;
@compatibility_alias ImageSettings PTImageSettings;
@compatibility_alias Ink PTInk;
@compatibility_alias LineAnnot PTLineAnnot;
@compatibility_alias Link PTLink;
@compatibility_alias LinkInfo PTLinkInfo;
@compatibility_alias MappedFile PTMappedFile;
@compatibility_alias Markup PTMarkup;
@compatibility_alias Matrix2D PTMatrix2D;
@compatibility_alias MonoImageSettings PTMonoImageSettings;
@compatibility_alias Movie PTMovie;
@compatibility_alias NameTree PTNameTree;
@compatibility_alias NumberTree PTNumberTree;
@compatibility_alias Obj PTObj;
@compatibility_alias ObjSet PTObjSet;
@compatibility_alias OCMD PTOCMD;
@compatibility_alias Optimizer PTOptimizer;
@compatibility_alias OptimizerSettings PTOptimizerSettings;
@compatibility_alias Page PTPage;
@compatibility_alias PageIterator PTPageIterator;
@compatibility_alias PageLabel PTPageLabel;
@compatibility_alias PageSet PTPageSet;
@compatibility_alias PathData PTPathData;
@compatibility_alias PatternColor PTPatternColor;
@compatibility_alias PDFACompliance PTPDFACompliance;
@compatibility_alias PDFDoc PTPDFDoc;
@compatibility_alias PDFDocInfo PTPDFDocInfo;
@compatibility_alias PDFDocViewPrefs PTPDFDocViewPrefs;
@compatibility_alias PDFDraw PTPDFDraw;
@compatibility_alias PDFNet PTPDFNet;
@compatibility_alias PDFPoint PTPDFPoint;
@compatibility_alias PDFRasterizer PTPDFRasterizer;
@compatibility_alias PDFRect PTPDFRect;
@compatibility_alias PDFView PTPDFView;
@compatibility_alias PDFPolygon PTPolygon;
@compatibility_alias PolyLine PTPolyLine;
@compatibility_alias Popup PTPopup;
@compatibility_alias Proxy PTProxy;
@compatibility_alias QuadPoint PTQuadPoint;
@compatibility_alias RecentlyUsedCache PTRecentlyUsedCache;
@compatibility_alias Redaction PTRedaction;
@compatibility_alias RedactionAnnot PTRedactionAnnot;
@compatibility_alias Redactor PTRedactor;
@compatibility_alias RoleMap PTRoleMap;
@compatibility_alias RubberStamp PTRubberStamp;
@compatibility_alias Screen PTScreen;
@compatibility_alias SDFDoc PTSDFDoc;
@compatibility_alias SearchResult PTSearchResult;
@compatibility_alias SecurityHandler PTSecurityHandler;
@compatibility_alias Selection PTSelection;
@compatibility_alias SElement PTSElement;
@compatibility_alias Shading PTShading;
@compatibility_alias SignatureHandler PTSignatureHandler;
@compatibility_alias Sound PTSound;
@compatibility_alias Square PTSquare;
@compatibility_alias Squiggly PTSquiggly;
@compatibility_alias Stamper PTStamper;
@compatibility_alias STree PTSTree;
@compatibility_alias StrikeOut PTStrikeOut;
@compatibility_alias SVGOutputOptions PTSVGOutputOptions;
@compatibility_alias Text PTText;
@compatibility_alias TextExtractor PTTextExtractor;
@compatibility_alias TextExtractorLine PTTextExtractorLine;
@compatibility_alias TextExtractorStyle PTTextExtractorStyle;
@compatibility_alias TextMarkup PTTextMarkup;
@compatibility_alias TextSearch PTTextSearch;
@compatibility_alias TextSettings PTTextSettings;
@compatibility_alias TOCSettings PTTOCSettings;
@compatibility_alias Underline PTUnderline;
@compatibility_alias Watermark PTWatermark;
@compatibility_alias WebPageSettings PTWebPageSettings;
@compatibility_alias Widget PTWidget;
@compatibility_alias Word PTWord;
@compatibility_alias XODOutputOptions PTXODOutputOptions;
@compatibility_alias XPSOutputCommonOptions PTXPSOutputCommonOptions;
@compatibility_alias XPSOutputOptions PTXPSOutputOptions;

@compatibility_alias TRNField PTField;
@compatibility_alias UInt32Iterator PTUInt32Iterator;

@compatibility_alias VectorObj PTVectorObj;
@compatibility_alias VectorPage PTVectorPage;
@compatibility_alias VectorQuadPoint PTVectorQuadPoint;
@compatibility_alias VectorRedaction PTVectorRedaction;
@compatibility_alias VectorString PTVectorString;

#endif
