#ifndef PDFNetOBJC_Private_H
#define PDFNetOBJC_Private_H

#import <Foundation/Foundation.h>
@class PTPDFDoc;
@class PTPrinterMode;
@class PTDictIterator;
@class PTAnnot;
@class PTField;
@class PTSElement;
@class PTSDFDoc;
@class PTPDFRect;
@class PTContext;
@class PTObj;
@class PTRedaction;
@class PTQuadPoint;
@class PTPage;
@class PTPatternColor;
@class PTFont;
@class PTSecurityHandler;
@class PTSignatureHandler;
@class PTColorPt;
@class PTHTTPRequestOptions;
@class PTSelection;
typedef size_t SignatureHandlerId;
typedef SignatureHandlerId PTSignatureHandlerId;
@class PTBorderStyle;
@class PTImageSettings;
@class PTMonoImageSettings;
@class PTTextSettings;
@class PTOptimizerSettings;
@class PTTextExtractorLine;
@class PTTextExtractorStyle;
@class PTWord;
@class PTXPSOutputCommonOptions;
@class PTXODOutputOptions;
@class PTXPSOutputOptions;
@class PTTiffOutputOptions;
@class PTHTMLOutputOptions;
@class PTWordOutputOptions;
@class PTEPUBOutputOptions;
@class PTSVGOutputOptions;
@class PTHighlight;
@class PTProxy;
@class PTWebPageSettings;
@class PTTOCSettings;
@class PTRedaction;
@class PTAppearance;
@class PTSeparation;
@class PTRadioButtonGroup;
@class PTEmbeddedTimestampVerificationResult;
@class PTX501AttributeTypeAndValue;
@class PTX509Extension;
@class PTX509Certificate;
@class PTDisallowedChange;
@class PTByteRange;
/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 2.0.1
 *
 * Do not make changes to this file unless you know what you are doing--modify
 * the SWIG interface file instead.
 * ----------------------------------------------------------------------------- */






#endif // PDFNetOBJC_Private_H

