//---------------------------------------------------------------------------------------
// Copyright (c) 2001-2021 by PDFTron Systems Inc. All Rights Reserved.
// Consult legal.txt regarding legal and license information.
//---------------------------------------------------------------------------------------
// !Warning! This file is autogenerated, modify the .codegen file, not this one
// (any changes here will be wiped out during the autogen process)

#ifndef PDFTRON_H_CDocSnapshot
#define PDFTRON_H_CDocSnapshot

#ifdef __cplusplus
extern "C" {
#endif

#include <C/Common/TRN_Types.h>
#include <C/Common/TRN_Exception.h>


struct TRN_DocSnapshot_tag;
typedef struct TRN_DocSnapshot_tag* TRN_DocSnapshot;


/* methods: */
TRN_API TRN_DocSnapshotGetHash(TRN_DocSnapshot self, TRN_UInt32* result);
TRN_API TRN_DocSnapshotIsValid(TRN_DocSnapshot self, TRN_Bool* result);
TRN_API TRN_DocSnapshotEquals(TRN_DocSnapshot self, TRN_DocSnapshot snapshot, TRN_Bool* result);

TRN_API TRN_DocSnapshotDestroy(TRN_DocSnapshot self);


#ifdef __cplusplus
} // extern C
#endif

#endif /* PDFTRON_H_CDocSnapshot */
