//---------------------------------------------------------------------------------------
// Copyright (c) 2001-2021 by PDFTron Systems Inc. All Rights Reserved.
// Consult legal.txt regarding legal and license information.
//---------------------------------------------------------------------------------------
// !Warning! This file is autogenerated, modify the .codegen file, not this one
// (any changes here will be wiped out during the autogen process)

#ifndef PDFTRON_H_CDocumentConversion
#define PDFTRON_H_CDocumentConversion

#ifdef __cplusplus
extern "C" {
#endif

#include <C/Common/TRN_Types.h>
#include <C/Common/TRN_Exception.h>


struct TRN_DocumentConversion_tag;
typedef struct TRN_DocumentConversion_tag* TRN_DocumentConversion;

/* enums:  */
enum TRN_DocumentConversion_Result {
	e_DocumentConversion_Success = 0,
	e_DocumentConversion_Incomplete = 1,
	e_DocumentConversion_Failure = 2
};

/* methods: */
TRN_API TRN_DocumentConversionTryConvert(TRN_DocumentConversion self, enum TRN_DocumentConversion_Result* result);
TRN_API TRN_DocumentConversionConvert(TRN_DocumentConversion self);
TRN_API TRN_DocumentConversionConvertNextPage(TRN_DocumentConversion self);
TRN_API TRN_DocumentConversionGetDoc(TRN_DocumentConversion self, TRN_PDFDoc* result);
TRN_API TRN_DocumentConversionGetConversionStatus(TRN_DocumentConversion self, enum TRN_DocumentConversion_Result* result);
TRN_API TRN_DocumentConversionCancelConversion(TRN_DocumentConversion self);
TRN_API TRN_DocumentConversionIsCancelled(TRN_DocumentConversion self, TRN_Bool* result);
TRN_API TRN_DocumentConversionHasProgressTracking(TRN_DocumentConversion self, TRN_Bool* result);
TRN_API TRN_DocumentConversionGetProgress(TRN_DocumentConversion self, double* result);
TRN_API TRN_DocumentConversionGetProgressLabel(TRN_DocumentConversion self, TRN_UString* result);
TRN_API TRN_DocumentConversionGetNumConvertedPages(TRN_DocumentConversion self, TRN_UInt32* result);
TRN_API TRN_DocumentConversionGetErrorString(TRN_DocumentConversion self, TRN_UString* result);
TRN_API TRN_DocumentConversionGetNumWarnings(TRN_DocumentConversion self, TRN_UInt32* result);
TRN_API TRN_DocumentConversionGetWarningString(TRN_DocumentConversion self, TRN_UInt32 index, TRN_UString* result);

TRN_API TRN_DocumentConversionDestroy(TRN_DocumentConversion* self);


#ifdef __cplusplus
} // extern C
#endif

#endif /* PDFTRON_H_CDocumentConversion */
