//---------------------------------------------------------------------------------------
// Copyright (c) 2001-2021 by PDFTron Systems Inc. All Rights Reserved.
// Consult legal.txt regarding legal and license information.
//---------------------------------------------------------------------------------------
// !Warning! This file is autogenerated, modify the .codegen file, not this one
// (any changes here will be wiped out during the autogen process)

#ifndef PDFTRON_H_CCertificateStatus
#define PDFTRON_H_CCertificateStatus

#ifdef __cplusplus
extern "C" {
#endif

#include <C/Common/TRN_Types.h>
#include <C/Common/TRN_Exception.h>


struct TRN_CertificateStatus_tag;
typedef struct TRN_CertificateStatus_tag* TRN_CertificateStatus;


/* methods: */
TRN_API TRN_CertificateStatusToString(TRN_CertificateStatus self, TRN_UString* result);

TRN_API TRN_CertificateStatusDestroy(TRN_CertificateStatus self);


#ifdef __cplusplus
} // extern C
#endif

#endif /* PDFTRON_H_CCertificateStatus */
