// This file is autogenerated: please see the codegen template "Options"
#ifndef PDFTRON_H_CPPPDFAdvancedImagingConvertOptions
#define PDFTRON_H_CPPPDFAdvancedImagingConvertOptions

#include <PDF/OptionsBase.h>

namespace pdftron{ namespace PDF{ 

class AdvancedImagingConvertOptions
{
public:
	AdvancedImagingConvertOptions();
	~AdvancedImagingConvertOptions();

	
	/**
	* Gets the value DefaultDPI from the options object
	* Default dpi used when rendering content when resolution is not provided in the image file. No image pixel data is lost by specifiying this option. Note: In case of DICOM images, we assume that the resolution is specified by Pixel Spacing attribute.
	* @ return a double, the current value for DefaultDPI.
	*/
	double GetDefaultDPI();

	/**
	* Sets the value for DefaultDPI in the options object
	* Default dpi used when rendering content when resolution is not provided in the image file. No image pixel data is lost by specifiying this option. Note: In case of DICOM images, we assume that the resolution is specified by Pixel Spacing attribute.
	* @param value: the new value for DefaultDPI
	* @return this object, for call chaining
	*/
	AdvancedImagingConvertOptions& SetDefaultDPI(double value);

	
	// @cond PRIVATE_DOC
	#ifndef SWIGHIDDEN
	SDF::Obj& GetInternalObj();

private:
	
	SDF::ObjSet m_obj_set;
	SDF::Obj m_dict;
	#endif
	// @endcond
};

}
}

#include "../Impl/AdvancedImagingConvertOptions.inl"
#endif // PDFTRON_H_CPPPDFAdvancedImagingConvertOptions
