package pdftron
/*
#include <stdint.h>
#define intgo swig_intgo
# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif

typedef long long intgo;
typedef unsigned long long uintgo;


typedef struct { char *p; intgo n; } _gostring_;

typedef long long swig_type_1;
typedef long long swig_type_2;
typedef long long swig_type_3;
typedef long long swig_type_4;
typedef long long swig_type_5;
typedef long long swig_type_6;
typedef long long swig_type_7;
typedef long long swig_type_8;
typedef long long swig_type_9;
typedef long long swig_type_10;
typedef long long swig_type_11;
typedef long long swig_type_12;
typedef long long swig_type_13;
typedef long long swig_type_14;
typedef long long swig_type_15;
typedef long long swig_type_16;
typedef long long swig_type_17;
typedef long long swig_type_18;
typedef long long swig_type_19;
typedef long long swig_type_20;
typedef long long swig_type_21;
typedef long long swig_type_22;
typedef long long swig_type_23;
typedef long long swig_type_24;
typedef long long swig_type_25;
typedef long long swig_type_26;
typedef long long swig_type_27;
typedef long long swig_type_28;
typedef long long swig_type_29;
typedef long long swig_type_30;
typedef long long swig_type_31;
typedef long long swig_type_32;
typedef _gostring_ swig_type_33;
typedef _gostring_ swig_type_34;
typedef _gostring_ swig_type_35;
typedef long long swig_type_36;
typedef long long swig_type_37;
typedef long long swig_type_38;
typedef long long swig_type_39;
typedef long long swig_type_40;
typedef long long swig_type_41;
typedef long long swig_type_42;
typedef long long swig_type_43;
typedef long long swig_type_44;
typedef long long swig_type_45;
typedef long long swig_type_46;
typedef long long swig_type_47;
typedef long long swig_type_48;
typedef long long swig_type_49;
typedef long long swig_type_50;
typedef long long swig_type_51;
typedef long long swig_type_52;
typedef long long swig_type_53;
typedef long long swig_type_54;
typedef long long swig_type_55;
typedef long long swig_type_56;
typedef long long swig_type_57;
typedef long long swig_type_58;
typedef long long swig_type_59;
typedef long long swig_type_60;
typedef long long swig_type_61;
typedef long long swig_type_62;
typedef long long swig_type_63;
typedef long long swig_type_64;
typedef long long swig_type_65;
typedef long long swig_type_66;
typedef long long swig_type_67;
typedef long long swig_type_68;
typedef long long swig_type_69;
typedef long long swig_type_70;
typedef long long swig_type_71;
typedef long long swig_type_72;
typedef long long swig_type_73;
typedef long long swig_type_74;
typedef long long swig_type_75;
typedef _gostring_ swig_type_76;
typedef _gostring_ swig_type_77;
typedef _gostring_ swig_type_78;
typedef _gostring_ swig_type_79;
typedef _gostring_ swig_type_80;
typedef _gostring_ swig_type_81;
typedef _gostring_ swig_type_82;
typedef long long swig_type_83;
typedef _gostring_ swig_type_84;
typedef _gostring_ swig_type_85;
typedef _gostring_ swig_type_86;
typedef _gostring_ swig_type_87;
typedef _gostring_ swig_type_88;
typedef _gostring_ swig_type_89;
typedef _gostring_ swig_type_90;
typedef _gostring_ swig_type_91;
typedef long long swig_type_92;
typedef _gostring_ swig_type_93;
typedef _gostring_ swig_type_94;
typedef _gostring_ swig_type_95;
typedef _gostring_ swig_type_96;
typedef _gostring_ swig_type_97;
typedef _gostring_ swig_type_98;
typedef _gostring_ swig_type_99;
typedef _gostring_ swig_type_100;
typedef void* swig_type_101;
typedef void* swig_type_102;
typedef _gostring_ swig_type_103;
typedef _gostring_ swig_type_104;
typedef long long swig_type_105;
typedef long long swig_type_106;
typedef _gostring_ swig_type_107;
typedef _gostring_ swig_type_108;
typedef long long swig_type_109;
typedef long long swig_type_110;
typedef long long swig_type_111;
typedef long long swig_type_112;
typedef _gostring_ swig_type_113;
typedef _gostring_ swig_type_114;
typedef _gostring_ swig_type_115;
typedef _gostring_ swig_type_116;
typedef _gostring_ swig_type_117;
typedef _gostring_ swig_type_118;
typedef _gostring_ swig_type_119;
typedef _gostring_ swig_type_120;
typedef _gostring_ swig_type_121;
typedef _gostring_ swig_type_122;
typedef _gostring_ swig_type_123;
typedef _gostring_ swig_type_124;
typedef _gostring_ swig_type_125;
typedef _gostring_ swig_type_126;
typedef _gostring_ swig_type_127;
typedef long long swig_type_128;
typedef long long swig_type_129;
typedef long long swig_type_130;
typedef long long swig_type_131;
typedef long long swig_type_132;
typedef long long swig_type_133;
typedef _gostring_ swig_type_134;
typedef _gostring_ swig_type_135;
typedef long long swig_type_136;
typedef _gostring_ swig_type_137;
typedef _gostring_ swig_type_138;
typedef long long swig_type_139;
typedef long long swig_type_140;
typedef long long swig_type_141;
typedef long long swig_type_142;
typedef long long swig_type_143;
typedef long long swig_type_144;
typedef _gostring_ swig_type_145;
typedef _gostring_ swig_type_146;
typedef long long swig_type_147;
typedef long long swig_type_148;
typedef long long swig_type_149;
typedef long long swig_type_150;
typedef _gostring_ swig_type_151;
typedef _gostring_ swig_type_152;
typedef _gostring_ swig_type_153;
typedef _gostring_ swig_type_154;
typedef long long swig_type_155;
typedef long long swig_type_156;
typedef long long swig_type_157;
typedef _gostring_ swig_type_158;
typedef _gostring_ swig_type_159;
typedef long long swig_type_160;
typedef long long swig_type_161;
typedef long long swig_type_162;
typedef _gostring_ swig_type_163;
typedef _gostring_ swig_type_164;
typedef _gostring_ swig_type_165;
typedef _gostring_ swig_type_166;
typedef long long swig_type_167;
typedef _gostring_ swig_type_168;
typedef _gostring_ swig_type_169;
typedef long long swig_type_170;
typedef long long swig_type_171;
typedef long long swig_type_172;
typedef _gostring_ swig_type_173;
typedef long long swig_type_174;
typedef _gostring_ swig_type_175;
typedef _gostring_ swig_type_176;
typedef long long swig_type_177;
typedef long long swig_type_178;
typedef long long swig_type_179;
typedef _gostring_ swig_type_180;
typedef _gostring_ swig_type_181;
typedef _gostring_ swig_type_182;
typedef long long swig_type_183;
typedef _gostring_ swig_type_184;
typedef _gostring_ swig_type_185;
typedef _gostring_ swig_type_186;
typedef _gostring_ swig_type_187;
typedef _gostring_ swig_type_188;
typedef _gostring_ swig_type_189;
typedef _gostring_ swig_type_190;
typedef _gostring_ swig_type_191;
typedef _gostring_ swig_type_192;
typedef _gostring_ swig_type_193;
typedef long long swig_type_194;
typedef _gostring_ swig_type_195;
typedef long long swig_type_196;
typedef _gostring_ swig_type_197;
typedef _gostring_ swig_type_198;
typedef _gostring_ swig_type_199;
typedef long long swig_type_200;
typedef long long swig_type_201;
typedef _gostring_ swig_type_202;
typedef long long swig_type_203;
typedef _gostring_ swig_type_204;
typedef _gostring_ swig_type_205;
typedef _gostring_ swig_type_206;
typedef _gostring_ swig_type_207;
typedef _gostring_ swig_type_208;
typedef _gostring_ swig_type_209;
typedef _gostring_ swig_type_210;
typedef _gostring_ swig_type_211;
typedef _gostring_ swig_type_212;
typedef _gostring_ swig_type_213;
typedef _gostring_ swig_type_214;
typedef _gostring_ swig_type_215;
typedef _gostring_ swig_type_216;
typedef _gostring_ swig_type_217;
typedef _gostring_ swig_type_218;
typedef _gostring_ swig_type_219;
typedef _gostring_ swig_type_220;
typedef _gostring_ swig_type_221;
typedef _gostring_ swig_type_222;
typedef _gostring_ swig_type_223;
typedef _gostring_ swig_type_224;
typedef _gostring_ swig_type_225;
typedef _gostring_ swig_type_226;
typedef _gostring_ swig_type_227;
typedef _gostring_ swig_type_228;
typedef long long swig_type_229;
typedef long long swig_type_230;
typedef _gostring_ swig_type_231;
typedef long long swig_type_232;
typedef long long swig_type_233;
typedef long long swig_type_234;
typedef long long swig_type_235;
typedef long long swig_type_236;
typedef _gostring_ swig_type_237;
typedef long long swig_type_238;
typedef _gostring_ swig_type_239;
typedef long long swig_type_240;
typedef _gostring_ swig_type_241;
typedef long long swig_type_242;
typedef long long swig_type_243;
typedef long long swig_type_244;
typedef long long swig_type_245;
typedef _gostring_ swig_type_246;
typedef _gostring_ swig_type_247;
typedef _gostring_ swig_type_248;
typedef _gostring_ swig_type_249;
typedef long long swig_type_250;
typedef long long swig_type_251;
typedef _gostring_ swig_type_252;
typedef long long swig_type_253;
typedef _gostring_ swig_type_254;
typedef long long swig_type_255;
typedef _gostring_ swig_type_256;
typedef _gostring_ swig_type_257;
typedef _gostring_ swig_type_258;
typedef _gostring_ swig_type_259;
typedef _gostring_ swig_type_260;
typedef _gostring_ swig_type_261;
typedef _gostring_ swig_type_262;
typedef long long swig_type_263;
typedef _gostring_ swig_type_264;
typedef _gostring_ swig_type_265;
typedef long long swig_type_266;
typedef _gostring_ swig_type_267;
typedef _gostring_ swig_type_268;
typedef long long swig_type_269;
typedef _gostring_ swig_type_270;
typedef _gostring_ swig_type_271;
typedef long long swig_type_272;
typedef _gostring_ swig_type_273;
typedef _gostring_ swig_type_274;
typedef long long swig_type_275;
typedef _gostring_ swig_type_276;
typedef _gostring_ swig_type_277;
typedef long long swig_type_278;
typedef long long swig_type_279;
typedef long long swig_type_280;
typedef _gostring_ swig_type_281;
typedef _gostring_ swig_type_282;
typedef _gostring_ swig_type_283;
typedef _gostring_ swig_type_284;
typedef _gostring_ swig_type_285;
typedef _gostring_ swig_type_286;
typedef _gostring_ swig_type_287;
typedef _gostring_ swig_type_288;
typedef _gostring_ swig_type_289;
typedef _gostring_ swig_type_290;
typedef long long swig_type_291;
typedef _gostring_ swig_type_292;
typedef _gostring_ swig_type_293;
typedef _gostring_ swig_type_294;
typedef _gostring_ swig_type_295;
typedef _gostring_ swig_type_296;
typedef long long swig_type_297;
typedef _gostring_ swig_type_298;
typedef _gostring_ swig_type_299;
typedef long long swig_type_300;
typedef long long swig_type_301;
typedef _gostring_ swig_type_302;
typedef _gostring_ swig_type_303;
typedef _gostring_ swig_type_304;
typedef _gostring_ swig_type_305;
typedef long long swig_type_306;
typedef _gostring_ swig_type_307;
typedef long long swig_type_308;
typedef _gostring_ swig_type_309;
typedef long long swig_type_310;
typedef _gostring_ swig_type_311;
typedef _gostring_ swig_type_312;
typedef _gostring_ swig_type_313;
typedef _gostring_ swig_type_314;
typedef _gostring_ swig_type_315;
typedef _gostring_ swig_type_316;
typedef _gostring_ swig_type_317;
typedef _gostring_ swig_type_318;
typedef _gostring_ swig_type_319;
typedef _gostring_ swig_type_320;
typedef _gostring_ swig_type_321;
typedef _gostring_ swig_type_322;
typedef _gostring_ swig_type_323;
typedef _gostring_ swig_type_324;
typedef _gostring_ swig_type_325;
typedef _gostring_ swig_type_326;
typedef long long swig_type_327;
typedef _gostring_ swig_type_328;
typedef long long swig_type_329;
typedef _gostring_ swig_type_330;
typedef _gostring_ swig_type_331;
typedef long long swig_type_332;
typedef _gostring_ swig_type_333;
typedef long long swig_type_334;
typedef _gostring_ swig_type_335;
typedef _gostring_ swig_type_336;
typedef _gostring_ swig_type_337;
typedef _gostring_ swig_type_338;
typedef _gostring_ swig_type_339;
typedef _gostring_ swig_type_340;
typedef _gostring_ swig_type_341;
typedef _gostring_ swig_type_342;
typedef _gostring_ swig_type_343;
typedef _gostring_ swig_type_344;
typedef _gostring_ swig_type_345;
typedef _gostring_ swig_type_346;
typedef _gostring_ swig_type_347;
typedef _gostring_ swig_type_348;
typedef _gostring_ swig_type_349;
typedef _gostring_ swig_type_350;
typedef _gostring_ swig_type_351;
typedef _gostring_ swig_type_352;
typedef _gostring_ swig_type_353;
typedef _gostring_ swig_type_354;
typedef _gostring_ swig_type_355;
typedef _gostring_ swig_type_356;
typedef _gostring_ swig_type_357;
typedef _gostring_ swig_type_358;
typedef _gostring_ swig_type_359;
typedef _gostring_ swig_type_360;
typedef _gostring_ swig_type_361;
typedef _gostring_ swig_type_362;
typedef _gostring_ swig_type_363;
typedef _gostring_ swig_type_364;
typedef _gostring_ swig_type_365;
typedef _gostring_ swig_type_366;
typedef _gostring_ swig_type_367;
typedef _gostring_ swig_type_368;
typedef _gostring_ swig_type_369;
typedef _gostring_ swig_type_370;
typedef _gostring_ swig_type_371;
typedef _gostring_ swig_type_372;
typedef _gostring_ swig_type_373;
typedef _gostring_ swig_type_374;
typedef _gostring_ swig_type_375;
typedef _gostring_ swig_type_376;
typedef _gostring_ swig_type_377;
typedef _gostring_ swig_type_378;
typedef _gostring_ swig_type_379;
typedef _gostring_ swig_type_380;
typedef _gostring_ swig_type_381;
typedef _gostring_ swig_type_382;
typedef _gostring_ swig_type_383;
typedef _gostring_ swig_type_384;
typedef _gostring_ swig_type_385;
typedef _gostring_ swig_type_386;
typedef _gostring_ swig_type_387;
typedef _gostring_ swig_type_388;
typedef _gostring_ swig_type_389;
typedef _gostring_ swig_type_390;
typedef _gostring_ swig_type_391;
typedef _gostring_ swig_type_392;
typedef _gostring_ swig_type_393;
typedef _gostring_ swig_type_394;
typedef _gostring_ swig_type_395;
typedef _gostring_ swig_type_396;
typedef _gostring_ swig_type_397;
typedef _gostring_ swig_type_398;
typedef _gostring_ swig_type_399;
typedef _gostring_ swig_type_400;
typedef _gostring_ swig_type_401;
typedef _gostring_ swig_type_402;
typedef _gostring_ swig_type_403;
typedef _gostring_ swig_type_404;
typedef _gostring_ swig_type_405;
typedef _gostring_ swig_type_406;
typedef _gostring_ swig_type_407;
typedef _gostring_ swig_type_408;
typedef _gostring_ swig_type_409;
typedef _gostring_ swig_type_410;
typedef _gostring_ swig_type_411;
typedef long long swig_type_412;
typedef _gostring_ swig_type_413;
typedef _gostring_ swig_type_414;
typedef _gostring_ swig_type_415;
typedef _gostring_ swig_type_416;
typedef _gostring_ swig_type_417;
typedef _gostring_ swig_type_418;
typedef _gostring_ swig_type_419;
typedef _gostring_ swig_type_420;
typedef _gostring_ swig_type_421;
typedef _gostring_ swig_type_422;
typedef _gostring_ swig_type_423;
typedef _gostring_ swig_type_424;
typedef _gostring_ swig_type_425;
typedef _gostring_ swig_type_426;
typedef _gostring_ swig_type_427;
typedef _gostring_ swig_type_428;
typedef _gostring_ swig_type_429;
typedef _gostring_ swig_type_430;
typedef _gostring_ swig_type_431;
typedef _gostring_ swig_type_432;
typedef _gostring_ swig_type_433;
typedef _gostring_ swig_type_434;
typedef _gostring_ swig_type_435;
typedef _gostring_ swig_type_436;
typedef _gostring_ swig_type_437;
typedef _gostring_ swig_type_438;
typedef _gostring_ swig_type_439;
typedef _gostring_ swig_type_440;
typedef _gostring_ swig_type_441;
typedef _gostring_ swig_type_442;
typedef _gostring_ swig_type_443;
typedef _gostring_ swig_type_444;
typedef _gostring_ swig_type_445;
typedef _gostring_ swig_type_446;
typedef _gostring_ swig_type_447;
typedef _gostring_ swig_type_448;
typedef _gostring_ swig_type_449;
typedef _gostring_ swig_type_450;
typedef _gostring_ swig_type_451;
typedef long long swig_type_452;
typedef _gostring_ swig_type_453;
typedef _gostring_ swig_type_454;
typedef long long swig_type_455;
typedef _gostring_ swig_type_456;
typedef _gostring_ swig_type_457;
typedef long long swig_type_458;
typedef _gostring_ swig_type_459;
typedef _gostring_ swig_type_460;
typedef long long swig_type_461;
typedef _gostring_ swig_type_462;
typedef _gostring_ swig_type_463;
typedef long long swig_type_464;
typedef _gostring_ swig_type_465;
typedef _gostring_ swig_type_466;
typedef long long swig_type_467;
typedef _gostring_ swig_type_468;
typedef _gostring_ swig_type_469;
typedef long long swig_type_470;
typedef _gostring_ swig_type_471;
typedef _gostring_ swig_type_472;
typedef long long swig_type_473;
typedef long long swig_type_474;
typedef long long swig_type_475;
typedef long long swig_type_476;
typedef long long swig_type_477;
typedef _gostring_ swig_type_478;
typedef _gostring_ swig_type_479;
typedef _gostring_ swig_type_480;
typedef _gostring_ swig_type_481;
typedef _gostring_ swig_type_482;
typedef _gostring_ swig_type_483;
typedef _gostring_ swig_type_484;
typedef _gostring_ swig_type_485;
typedef _gostring_ swig_type_486;
typedef _gostring_ swig_type_487;
typedef _gostring_ swig_type_488;
typedef _gostring_ swig_type_489;
typedef _gostring_ swig_type_490;
typedef _gostring_ swig_type_491;
typedef _gostring_ swig_type_492;
typedef _gostring_ swig_type_493;
typedef _gostring_ swig_type_494;
typedef _gostring_ swig_type_495;
typedef _gostring_ swig_type_496;
typedef _gostring_ swig_type_497;
typedef _gostring_ swig_type_498;
typedef _gostring_ swig_type_499;
typedef _gostring_ swig_type_500;
typedef _gostring_ swig_type_501;
typedef _gostring_ swig_type_502;
typedef _gostring_ swig_type_503;
typedef _gostring_ swig_type_504;
typedef _gostring_ swig_type_505;
typedef _gostring_ swig_type_506;
typedef _gostring_ swig_type_507;
typedef _gostring_ swig_type_508;
typedef _gostring_ swig_type_509;
typedef _gostring_ swig_type_510;
typedef _gostring_ swig_type_511;
typedef _gostring_ swig_type_512;
typedef _gostring_ swig_type_513;
typedef _gostring_ swig_type_514;
typedef _gostring_ swig_type_515;
typedef _gostring_ swig_type_516;
typedef _gostring_ swig_type_517;
typedef _gostring_ swig_type_518;
typedef long long swig_type_519;
typedef _gostring_ swig_type_520;
typedef _gostring_ swig_type_521;
typedef _gostring_ swig_type_522;
typedef _gostring_ swig_type_523;
typedef _gostring_ swig_type_524;
typedef _gostring_ swig_type_525;
typedef _gostring_ swig_type_526;
typedef _gostring_ swig_type_527;
typedef _gostring_ swig_type_528;
typedef _gostring_ swig_type_529;
typedef _gostring_ swig_type_530;
typedef _gostring_ swig_type_531;
typedef _gostring_ swig_type_532;
typedef _gostring_ swig_type_533;
typedef _gostring_ swig_type_534;
typedef _gostring_ swig_type_535;
typedef _gostring_ swig_type_536;
typedef _gostring_ swig_type_537;
typedef _gostring_ swig_type_538;
typedef _gostring_ swig_type_539;
typedef _gostring_ swig_type_540;
typedef _gostring_ swig_type_541;
typedef _gostring_ swig_type_542;
typedef _gostring_ swig_type_543;
typedef _gostring_ swig_type_544;
typedef _gostring_ swig_type_545;
typedef _gostring_ swig_type_546;
typedef _gostring_ swig_type_547;
typedef _gostring_ swig_type_548;
typedef _gostring_ swig_type_549;
typedef _gostring_ swig_type_550;
typedef _gostring_ swig_type_551;
typedef _gostring_ swig_type_552;
typedef _gostring_ swig_type_553;
typedef _gostring_ swig_type_554;
typedef _gostring_ swig_type_555;
typedef _gostring_ swig_type_556;
typedef _gostring_ swig_type_557;
typedef _gostring_ swig_type_558;
typedef _gostring_ swig_type_559;
typedef _gostring_ swig_type_560;
typedef _gostring_ swig_type_561;
typedef _gostring_ swig_type_562;
typedef _gostring_ swig_type_563;
typedef _gostring_ swig_type_564;
typedef _gostring_ swig_type_565;
typedef _gostring_ swig_type_566;
typedef _gostring_ swig_type_567;
typedef _gostring_ swig_type_568;
typedef _gostring_ swig_type_569;
typedef _gostring_ swig_type_570;
typedef _gostring_ swig_type_571;
typedef _gostring_ swig_type_572;
typedef _gostring_ swig_type_573;
typedef _gostring_ swig_type_574;
typedef _gostring_ swig_type_575;
typedef _gostring_ swig_type_576;
typedef _gostring_ swig_type_577;
typedef _gostring_ swig_type_578;
typedef _gostring_ swig_type_579;
typedef _gostring_ swig_type_580;
typedef _gostring_ swig_type_581;
typedef _gostring_ swig_type_582;
typedef _gostring_ swig_type_583;
typedef _gostring_ swig_type_584;
typedef _gostring_ swig_type_585;
typedef _gostring_ swig_type_586;
typedef _gostring_ swig_type_587;
typedef _gostring_ swig_type_588;
typedef _gostring_ swig_type_589;
typedef _gostring_ swig_type_590;
typedef _gostring_ swig_type_591;
typedef _gostring_ swig_type_592;
typedef _gostring_ swig_type_593;
typedef _gostring_ swig_type_594;
typedef _gostring_ swig_type_595;
typedef _gostring_ swig_type_596;
typedef _gostring_ swig_type_597;
typedef _gostring_ swig_type_598;
typedef _gostring_ swig_type_599;
typedef _gostring_ swig_type_600;
typedef _gostring_ swig_type_601;
typedef long long swig_type_602;
typedef long long swig_type_603;
typedef long long swig_type_604;
typedef long long swig_type_605;
typedef _gostring_ swig_type_606;
typedef long long swig_type_607;
typedef _gostring_ swig_type_608;
typedef long long swig_type_609;
typedef _gostring_ swig_type_610;
typedef long long swig_type_611;
typedef _gostring_ swig_type_612;
typedef long long swig_type_613;
typedef _gostring_ swig_type_614;
typedef long long swig_type_615;
typedef _gostring_ swig_type_616;
typedef _gostring_ swig_type_617;
typedef _gostring_ swig_type_618;
typedef _gostring_ swig_type_619;
typedef _gostring_ swig_type_620;
typedef _gostring_ swig_type_621;
typedef _gostring_ swig_type_622;
typedef _gostring_ swig_type_623;
typedef _gostring_ swig_type_624;
typedef _gostring_ swig_type_625;
typedef _gostring_ swig_type_626;
typedef _gostring_ swig_type_627;
typedef _gostring_ swig_type_628;
typedef _gostring_ swig_type_629;
typedef _gostring_ swig_type_630;
typedef _gostring_ swig_type_631;
typedef _gostring_ swig_type_632;
typedef _gostring_ swig_type_633;
typedef _gostring_ swig_type_634;
typedef _gostring_ swig_type_635;
typedef _gostring_ swig_type_636;
typedef _gostring_ swig_type_637;
typedef long long swig_type_638;
typedef _gostring_ swig_type_639;
typedef _gostring_ swig_type_640;
typedef long long swig_type_641;
typedef long long swig_type_642;
typedef _gostring_ swig_type_643;
typedef _gostring_ swig_type_644;
typedef long long swig_type_645;
typedef _gostring_ swig_type_646;
typedef long long swig_type_647;
typedef long long swig_type_648;
typedef _gostring_ swig_type_649;
typedef long long swig_type_650;
typedef long long swig_type_651;
typedef _gostring_ swig_type_652;
typedef _gostring_ swig_type_653;
typedef _gostring_ swig_type_654;
typedef _gostring_ swig_type_655;
typedef _gostring_ swig_type_656;
typedef _gostring_ swig_type_657;
typedef _gostring_ swig_type_658;
typedef _gostring_ swig_type_659;
typedef _gostring_ swig_type_660;
typedef _gostring_ swig_type_661;
typedef _gostring_ swig_type_662;
typedef _gostring_ swig_type_663;
typedef _gostring_ swig_type_664;
typedef _gostring_ swig_type_665;
typedef _gostring_ swig_type_666;
typedef _gostring_ swig_type_667;
typedef long long swig_type_668;
typedef _gostring_ swig_type_669;
typedef long long swig_type_670;
typedef _gostring_ swig_type_671;
typedef _gostring_ swig_type_672;
typedef _gostring_ swig_type_673;
typedef _gostring_ swig_type_674;
typedef _gostring_ swig_type_675;
typedef _gostring_ swig_type_676;
typedef _gostring_ swig_type_677;
typedef _gostring_ swig_type_678;
typedef _gostring_ swig_type_679;
typedef _gostring_ swig_type_680;
typedef _gostring_ swig_type_681;
typedef _gostring_ swig_type_682;
typedef _gostring_ swig_type_683;
typedef _gostring_ swig_type_684;
typedef _gostring_ swig_type_685;
typedef _gostring_ swig_type_686;
typedef _gostring_ swig_type_687;
typedef _gostring_ swig_type_688;
typedef _gostring_ swig_type_689;
typedef _gostring_ swig_type_690;
typedef _gostring_ swig_type_691;
typedef _gostring_ swig_type_692;
typedef _gostring_ swig_type_693;
typedef _gostring_ swig_type_694;
typedef _gostring_ swig_type_695;
typedef _gostring_ swig_type_696;
typedef _gostring_ swig_type_697;
typedef _gostring_ swig_type_698;
typedef _gostring_ swig_type_699;
typedef _gostring_ swig_type_700;
typedef _gostring_ swig_type_701;
typedef _gostring_ swig_type_702;
typedef _gostring_ swig_type_703;
typedef _gostring_ swig_type_704;
typedef _gostring_ swig_type_705;
typedef _gostring_ swig_type_706;
typedef _gostring_ swig_type_707;
typedef _gostring_ swig_type_708;
typedef _gostring_ swig_type_709;
typedef _gostring_ swig_type_710;
typedef _gostring_ swig_type_711;
typedef _gostring_ swig_type_712;
typedef _gostring_ swig_type_713;
typedef _gostring_ swig_type_714;
typedef _gostring_ swig_type_715;
typedef _gostring_ swig_type_716;
typedef _gostring_ swig_type_717;
typedef _gostring_ swig_type_718;
typedef _gostring_ swig_type_719;
typedef _gostring_ swig_type_720;
typedef _gostring_ swig_type_721;
typedef _gostring_ swig_type_722;
typedef _gostring_ swig_type_723;
typedef _gostring_ swig_type_724;
typedef _gostring_ swig_type_725;
typedef _gostring_ swig_type_726;
typedef _gostring_ swig_type_727;
typedef _gostring_ swig_type_728;
typedef _gostring_ swig_type_729;
typedef _gostring_ swig_type_730;
typedef _gostring_ swig_type_731;
typedef _gostring_ swig_type_732;
typedef _gostring_ swig_type_733;
typedef _gostring_ swig_type_734;
typedef _gostring_ swig_type_735;
typedef _gostring_ swig_type_736;
typedef _gostring_ swig_type_737;
typedef _gostring_ swig_type_738;
typedef _gostring_ swig_type_739;
typedef _gostring_ swig_type_740;
typedef _gostring_ swig_type_741;
typedef _gostring_ swig_type_742;
typedef _gostring_ swig_type_743;
typedef _gostring_ swig_type_744;
typedef _gostring_ swig_type_745;
typedef _gostring_ swig_type_746;
typedef _gostring_ swig_type_747;
typedef _gostring_ swig_type_748;
typedef _gostring_ swig_type_749;
typedef _gostring_ swig_type_750;
typedef _gostring_ swig_type_751;
typedef _gostring_ swig_type_752;
typedef _gostring_ swig_type_753;
typedef _gostring_ swig_type_754;
typedef _gostring_ swig_type_755;
typedef _gostring_ swig_type_756;
typedef _gostring_ swig_type_757;
typedef _gostring_ swig_type_758;
typedef _gostring_ swig_type_759;
typedef _gostring_ swig_type_760;
typedef _gostring_ swig_type_761;
typedef _gostring_ swig_type_762;
typedef _gostring_ swig_type_763;
typedef _gostring_ swig_type_764;
typedef _gostring_ swig_type_765;
typedef _gostring_ swig_type_766;
typedef _gostring_ swig_type_767;
typedef _gostring_ swig_type_768;
typedef _gostring_ swig_type_769;
typedef _gostring_ swig_type_770;
typedef _gostring_ swig_type_771;
typedef _gostring_ swig_type_772;
typedef _gostring_ swig_type_773;
typedef _gostring_ swig_type_774;
typedef _gostring_ swig_type_775;
typedef _gostring_ swig_type_776;
typedef _gostring_ swig_type_777;
typedef _gostring_ swig_type_778;
typedef _gostring_ swig_type_779;
typedef _gostring_ swig_type_780;
typedef _gostring_ swig_type_781;
typedef _gostring_ swig_type_782;
typedef _gostring_ swig_type_783;
typedef _gostring_ swig_type_784;
typedef _gostring_ swig_type_785;
typedef _gostring_ swig_type_786;
typedef _gostring_ swig_type_787;
typedef _gostring_ swig_type_788;
typedef _gostring_ swig_type_789;
typedef _gostring_ swig_type_790;
typedef _gostring_ swig_type_791;
typedef _gostring_ swig_type_792;
typedef _gostring_ swig_type_793;
typedef _gostring_ swig_type_794;
typedef _gostring_ swig_type_795;
typedef _gostring_ swig_type_796;
typedef _gostring_ swig_type_797;
typedef _gostring_ swig_type_798;
typedef _gostring_ swig_type_799;
typedef _gostring_ swig_type_800;
typedef _gostring_ swig_type_801;
typedef _gostring_ swig_type_802;
typedef _gostring_ swig_type_803;
typedef _gostring_ swig_type_804;
typedef _gostring_ swig_type_805;
typedef _gostring_ swig_type_806;
typedef _gostring_ swig_type_807;
typedef _gostring_ swig_type_808;
typedef _gostring_ swig_type_809;
typedef _gostring_ swig_type_810;
typedef _gostring_ swig_type_811;
typedef _gostring_ swig_type_812;
typedef _gostring_ swig_type_813;
typedef _gostring_ swig_type_814;
typedef _gostring_ swig_type_815;
typedef _gostring_ swig_type_816;
typedef _gostring_ swig_type_817;
typedef _gostring_ swig_type_818;
typedef _gostring_ swig_type_819;
typedef _gostring_ swig_type_820;
typedef _gostring_ swig_type_821;
typedef _gostring_ swig_type_822;
typedef _gostring_ swig_type_823;
typedef _gostring_ swig_type_824;
typedef _gostring_ swig_type_825;
typedef _gostring_ swig_type_826;
typedef _gostring_ swig_type_827;
typedef _gostring_ swig_type_828;
typedef _gostring_ swig_type_829;
typedef _gostring_ swig_type_830;
typedef _gostring_ swig_type_831;
typedef _gostring_ swig_type_832;
typedef _gostring_ swig_type_833;
typedef _gostring_ swig_type_834;
typedef _gostring_ swig_type_835;
typedef _gostring_ swig_type_836;
typedef _gostring_ swig_type_837;
typedef _gostring_ swig_type_838;
typedef _gostring_ swig_type_839;
typedef _gostring_ swig_type_840;
typedef _gostring_ swig_type_841;
typedef _gostring_ swig_type_842;
typedef _gostring_ swig_type_843;
typedef _gostring_ swig_type_844;
typedef _gostring_ swig_type_845;
typedef _gostring_ swig_type_846;
typedef _gostring_ swig_type_847;
typedef _gostring_ swig_type_848;
typedef _gostring_ swig_type_849;
typedef _gostring_ swig_type_850;
typedef _gostring_ swig_type_851;
typedef _gostring_ swig_type_852;
typedef _gostring_ swig_type_853;
typedef _gostring_ swig_type_854;
typedef _gostring_ swig_type_855;
typedef _gostring_ swig_type_856;
typedef _gostring_ swig_type_857;
typedef _gostring_ swig_type_858;
typedef _gostring_ swig_type_859;
typedef _gostring_ swig_type_860;
typedef _gostring_ swig_type_861;
typedef _gostring_ swig_type_862;
typedef _gostring_ swig_type_863;
typedef _gostring_ swig_type_864;
typedef _gostring_ swig_type_865;
typedef _gostring_ swig_type_866;
typedef _gostring_ swig_type_867;
typedef _gostring_ swig_type_868;
typedef _gostring_ swig_type_869;
typedef _gostring_ swig_type_870;
typedef _gostring_ swig_type_871;
typedef _gostring_ swig_type_872;
typedef _gostring_ swig_type_873;
typedef _gostring_ swig_type_874;
typedef _gostring_ swig_type_875;
typedef long long swig_type_876;
typedef long long swig_type_877;
typedef long long swig_type_878;
typedef _gostring_ swig_type_879;
typedef _gostring_ swig_type_880;
typedef _gostring_ swig_type_881;
typedef long long swig_type_882;
typedef long long swig_type_883;
typedef long long swig_type_884;
typedef _gostring_ swig_type_885;
typedef _gostring_ swig_type_886;
typedef _gostring_ swig_type_887;
typedef _gostring_ swig_type_888;
typedef _gostring_ swig_type_889;
typedef _gostring_ swig_type_890;
typedef _gostring_ swig_type_891;
typedef _gostring_ swig_type_892;
typedef _gostring_ swig_type_893;
typedef _gostring_ swig_type_894;
typedef _gostring_ swig_type_895;
typedef _gostring_ swig_type_896;
typedef _gostring_ swig_type_897;
typedef _gostring_ swig_type_898;
typedef _gostring_ swig_type_899;
typedef _gostring_ swig_type_900;
typedef _gostring_ swig_type_901;
typedef _gostring_ swig_type_902;
typedef _gostring_ swig_type_903;
typedef _gostring_ swig_type_904;
typedef _gostring_ swig_type_905;
typedef _gostring_ swig_type_906;
typedef _gostring_ swig_type_907;
typedef _gostring_ swig_type_908;
typedef _gostring_ swig_type_909;
typedef _gostring_ swig_type_910;
typedef _gostring_ swig_type_911;
typedef long long swig_type_912;
typedef _gostring_ swig_type_913;
typedef _gostring_ swig_type_914;
typedef _gostring_ swig_type_915;
typedef _gostring_ swig_type_916;
typedef _gostring_ swig_type_917;
typedef _gostring_ swig_type_918;
typedef long long swig_type_919;
typedef long long swig_type_920;
typedef long long swig_type_921;
typedef _gostring_ swig_type_922;
typedef _gostring_ swig_type_923;
typedef _gostring_ swig_type_924;
typedef _gostring_ swig_type_925;
typedef _gostring_ swig_type_926;
typedef _gostring_ swig_type_927;
typedef _gostring_ swig_type_928;
typedef _gostring_ swig_type_929;
typedef _gostring_ swig_type_930;
typedef _gostring_ swig_type_931;
typedef _gostring_ swig_type_932;
typedef _gostring_ swig_type_933;
typedef _gostring_ swig_type_934;
typedef _gostring_ swig_type_935;
typedef _gostring_ swig_type_936;
typedef _gostring_ swig_type_937;
typedef _gostring_ swig_type_938;
typedef _gostring_ swig_type_939;
typedef _gostring_ swig_type_940;
typedef _gostring_ swig_type_941;
typedef _gostring_ swig_type_942;
typedef _gostring_ swig_type_943;
typedef _gostring_ swig_type_944;
typedef _gostring_ swig_type_945;
typedef _gostring_ swig_type_946;
typedef _gostring_ swig_type_947;
typedef _gostring_ swig_type_948;
typedef _gostring_ swig_type_949;
typedef _gostring_ swig_type_950;
typedef _gostring_ swig_type_951;
typedef _gostring_ swig_type_952;
typedef _gostring_ swig_type_953;
typedef _gostring_ swig_type_954;
typedef _gostring_ swig_type_955;
typedef _gostring_ swig_type_956;
typedef _gostring_ swig_type_957;
typedef _gostring_ swig_type_958;
typedef _gostring_ swig_type_959;
typedef _gostring_ swig_type_960;
typedef _gostring_ swig_type_961;
typedef _gostring_ swig_type_962;
typedef _gostring_ swig_type_963;
typedef _gostring_ swig_type_964;
typedef _gostring_ swig_type_965;
typedef _gostring_ swig_type_966;
typedef _gostring_ swig_type_967;
typedef _gostring_ swig_type_968;
typedef _gostring_ swig_type_969;
typedef _gostring_ swig_type_970;
typedef _gostring_ swig_type_971;
typedef _gostring_ swig_type_972;
typedef _gostring_ swig_type_973;
typedef _gostring_ swig_type_974;
typedef _gostring_ swig_type_975;
typedef _gostring_ swig_type_976;
typedef _gostring_ swig_type_977;
typedef _gostring_ swig_type_978;
typedef _gostring_ swig_type_979;
typedef _gostring_ swig_type_980;
typedef _gostring_ swig_type_981;
typedef _gostring_ swig_type_982;
typedef _gostring_ swig_type_983;
typedef _gostring_ swig_type_984;
typedef _gostring_ swig_type_985;
typedef _gostring_ swig_type_986;
typedef _gostring_ swig_type_987;
typedef _gostring_ swig_type_988;
typedef _gostring_ swig_type_989;
typedef _gostring_ swig_type_990;
typedef _gostring_ swig_type_991;
typedef _gostring_ swig_type_992;
typedef _gostring_ swig_type_993;
typedef _gostring_ swig_type_994;
typedef _gostring_ swig_type_995;
typedef _gostring_ swig_type_996;
typedef _gostring_ swig_type_997;
typedef _gostring_ swig_type_998;

extern void crosscall2(void (*fn)(void *, int), void *, int);
extern void _cgo_panic(void *, int);
void cgo_panic_pdftron(char* message)
{
  struct {
    const char *p;
  } SWIGSTRUCTPACKED a;
  a.p = message;
  crosscall2(_cgo_panic, &a, (int) sizeof a);
}


void cgo_Swiggo_DeleteDirector_Callback_pdftron_5f1e8caadb3437e6(uintptr_t arg1)
{
	void Swiggo_DeleteDirector_Callback_pdftron_5f1e8caadb3437e6(uintptr_t);
	Swiggo_DeleteDirector_Callback_pdftron_5f1e8caadb3437e6(arg1);
}
void cgo_Swig_DirectorCallback_callback_RenderBeginEventProc_pdftron_5f1e8caadb3437e6(uintptr_t arg1)
{
	void Swig_DirectorCallback_callback_RenderBeginEventProc_pdftron_5f1e8caadb3437e6(uintptr_t);
	Swig_DirectorCallback_callback_RenderBeginEventProc_pdftron_5f1e8caadb3437e6(arg1);
}
void cgo_Swig_DirectorCallback_callback_RenderFinishEventProc_pdftron_5f1e8caadb3437e6(uintptr_t arg1, _Bool cancelled)
{
	void Swig_DirectorCallback_callback_RenderFinishEventProc_pdftron_5f1e8caadb3437e6(uintptr_t, _Bool);
	Swig_DirectorCallback_callback_RenderFinishEventProc_pdftron_5f1e8caadb3437e6(arg1, cancelled);
}
void cgo_Swig_DirectorCallback_callback_ErrorReportProc_pdftron_5f1e8caadb3437e6(uintptr_t arg1, _gostring_ message)
{
	void Swig_DirectorCallback_callback_ErrorReportProc_pdftron_5f1e8caadb3437e6(uintptr_t, _gostring_);
	Swig_DirectorCallback_callback_ErrorReportProc_pdftron_5f1e8caadb3437e6(arg1, message);
}


void cgo_Swig_DirectorCallback_callback_CurrentPageProc_pdftron_5f1e8caadb3437e6(uintptr_t arg1, swig_intgo current_page, swig_intgo num_pages)
{
   void Swig_DirectorCallback_callback_CurrentPageProc_pdftron_5f1e8caadb3437e6(uintptr_t, swig_intgo current_page, swig_intgo num_pages);
   Swig_DirectorCallback_callback_CurrentPageProc_pdftron_5f1e8caadb3437e6(arg1, current_page, num_pages);
}

void cgo_Swig_DirectorCallback_callback_JavaScriptEventProc_pdftron_5f1e8caadb3437e6(uintptr_t arg1, _gostring_ event_type, _gostring_ json)
{
	void Swig_DirectorCallback_callback_JavaScriptEventProc_pdftron_5f1e8caadb3437e6(uintptr_t, _gostring_ event_type, _gostring_ json);
	Swig_DirectorCallback_callback_JavaScriptEventProc_pdftron_5f1e8caadb3437e6(arg1,  event_type,  json);


}
void cgo_Swig_DirectorCallback_callback_CurrentZoomProc_pdftron_5f1e8caadb3437e6(uintptr_t arg1, double curr_zoom_proc)
{
	void Swig_DirectorCallback_callback_CurrentZoomProc_pdftron_5f1e8caadb3437e6(uintptr_t, double curr_zoom_proc);
	Swig_DirectorCallback_callback_CurrentZoomProc_pdftron_5f1e8caadb3437e6(arg1,  curr_zoom_proc);

}
void cgo_Swig_DirectorCallback_callback_ThumbAsyncHandler_pdftron_5f1e8caadb3437e6(uintptr_t arg1, swig_intgo page_num, _Bool was_thumb_found, _gostring_ thumb_buf, swig_intgo thumb_width, swig_intgo thumb_height)
{
	void Swig_DirectorCallback_callback_ThumbAsyncHandler_pdftron_5f1e8caadb3437e6(uintptr_t, swig_intgo page_num, _Bool was_thumb_found, _gostring_ thumb_buf, swig_intgo thumb_width, swig_intgo thumb_height);
	Swig_DirectorCallback_callback_ThumbAsyncHandler_pdftron_5f1e8caadb3437e6(arg1,  page_num,  was_thumb_found,  thumb_buf,  thumb_width,  thumb_height);

}

void cgo_Swig_DirectorCallback_callback_RequestRenderInWorkerThread_pdftron_5f1e8caadb3437e6(uintptr_t arg1)
{
	void Swig_DirectorCallback_callback_RequestRenderInWorkerThread_pdftron_5f1e8caadb3437e6(uintptr_t);
	Swig_DirectorCallback_callback_RequestRenderInWorkerThread_pdftron_5f1e8caadb3437e6(arg1);
}

void cgo_Swig_DirectorCallback_callback_FindTextHandler_pdftron_5f1e8caadb3437e6(uintptr_t arg1, _Bool success, uintptr_t selection)
{
	void Swig_DirectorCallback_callback_FindTextHandler_pdftron_5f1e8caadb3437e6(uintptr_t, _Bool success, uintptr_t selection);
	Swig_DirectorCallback_callback_FindTextHandler_pdftron_5f1e8caadb3437e6(arg1,  success,  selection);
}

void cgo_Swig_DirectorCallback_callback_CreateTileProc_pdftron_5f1e8caadb3437e6(uintptr_t arg1, _gostring_ buffer, swig_intgo originX, swig_intgo originY, swig_intgo width, swig_intgo height, swig_intgo pagNum, long long cellNumber, _Bool finalRender, _Bool predictionRender, swig_intgo tilesRemaining, _Bool firstTile, swig_intgo canvasWidth, swig_intgo canvasHeight, swig_intgo cellSideLength, swig_intgo cellPerRow, swig_intgo cellPerCol, swig_intgo thumbnailId)
{
	void Swig_DirectorCallback_callback_CreateTileProc_pdftron_5f1e8caadb3437e6(uintptr_t arg1, _gostring_ buffer, swig_intgo originX, swig_intgo originY, swig_intgo width, swig_intgo height, swig_intgo pagNum, long long cellNumber, _Bool finalRender, _Bool predictionRender, swig_intgo tilesRemaining, _Bool firstTile, swig_intgo canvasWidth, swig_intgo canvasHeight, swig_intgo cellSideLength, swig_intgo cellPerRow, swig_intgo cellPerCol, swig_intgo thumbnailId);
	Swig_DirectorCallback_callback_CreateTileProc_pdftron_5f1e8caadb3437e6(arg1,  buffer,  originX,  originY,  width,  height,  pagNum,  cellNumber,  finalRender,  predictionRender,  tilesRemaining,  firstTile,  canvasWidth,  canvasHeight,  cellSideLength,  cellPerRow,  cellPerCol,  thumbnailId);

}


void cgo_Swig_DirectorCallback_callback_AnnotBitmapProc_pdftron_5f1e8caadb3437e6(uintptr_t arg1, swig_intgo operation_type, _gostring_ buffer, uintptr_t width, uintptr_t height, uintptr_t stride, uintptr_t page_num, uintptr_t annot_index, uintptr_t annot_key, uintptr_t x_in_page, uintptr_t y_in_page, swig_intgo x_offset, swig_intgo y_offset, swig_intgo remaining_tiles, swig_intgo sequence_number, uintptr_t x_page_size, uintptr_t y_page_size)
{
	void Swig_DirectorCallback_callback_AnnotBitmapProc_pdftron_5f1e8caadb3437e6(uintptr_t, swig_intgo operation_type, _gostring_ buffer, uintptr_t width, uintptr_t height, uintptr_t stride, uintptr_t page_num, uintptr_t annot_index, uintptr_t annot_key, uintptr_t x_in_page, uintptr_t y_in_page, swig_intgo x_offset, swig_intgo y_offset, swig_intgo remaining_tiles, swig_intgo sequence_number, uintptr_t x_page_size, uintptr_t y_page_size);
	Swig_DirectorCallback_callback_AnnotBitmapProc_pdftron_5f1e8caadb3437e6(arg1,  operation_type,  buffer,  width,  height,  stride,  page_num,  annot_index,  annot_key,  x_in_page,  y_in_page,  x_offset,  y_offset,  remaining_tiles,  sequence_number,  x_page_size,  y_page_size);

}

void cgo_Swig_DirectorCallback_callback_DeluxeCreateTileProc_pdftron_5f1e8caadb3437e6(uintptr_t arg1, _gostring_ buffer, swig_intgo width, swig_intgo height, swig_intgo stride, swig_intgo page_num, uintptr_t x_page_loc, uintptr_t y_page_loc, swig_intgo zoomed_page_width, swig_intgo zoomed_page_height, swig_intgo tile_id, swig_intgo x_in_page, swig_intgo y_in_page, swig_intgo canvas_id, swig_intgo remaining_tiles, swig_intgo tile_type, swig_intgo sequence_number)
{
	void Swig_DirectorCallback_callback_DeluxeCreateTileProc_pdftron_5f1e8caadb3437e6(uintptr_t, _gostring_ buffer, swig_intgo width, swig_intgo height, swig_intgo stride, swig_intgo page_num, uintptr_t x_page_loc, uintptr_t y_page_loc, swig_intgo zoomed_page_width, swig_intgo zoomed_page_height, swig_intgo tile_id, swig_intgo x_in_page, swig_intgo y_in_page, swig_intgo canvas_id, swig_intgo remaining_tiles, swig_intgo tile_type, swig_intgo sequence_number);
	Swig_DirectorCallback_callback_DeluxeCreateTileProc_pdftron_5f1e8caadb3437e6(arg1,  buffer,  width,  height,  stride,  page_num,  x_page_loc,  y_page_loc,  zoomed_page_width,  zoomed_page_height,  tile_id,  x_in_page,  y_in_page,  canvas_id,  remaining_tiles,  tile_type,  sequence_number);

}

void cgo_Swig_DirectorCallback_callback_RemoveTileProc_pdftron_5f1e8caadb3437e6(uintptr_t arg1, swig_intgo canvasNumber, uintptr_t cellNumber, swig_intgo thumbnailId, swig_intgo sequenceNumber)
{
	void Swig_DirectorCallback_callback_RemoveTileProc_pdftron_5f1e8caadb3437e6(uintptr_t, swig_intgo canvasNumber, uintptr_t cellNumber, swig_intgo thumbnailId, swig_intgo sequenceNumber);
	Swig_DirectorCallback_callback_RemoveTileProc_pdftron_5f1e8caadb3437e6(arg1,  canvasNumber,  cellNumber,  thumbnailId,  sequenceNumber);

}

void cgo_Swig_DirectorCallback_callback_PartDownloadedProc_pdftron_5f1e8caadb3437e6(uintptr_t arg1, swig_intgo dlType, uintptr_t doc, swig_intgo pageNum, swig_intgo objNum, _gostring_ message)
{
	void Swig_DirectorCallback_callback_PartDownloadedProc_pdftron_5f1e8caadb3437e6(uintptr_t, swig_intgo dlType, uintptr_t doc, swig_intgo pageNum, swig_intgo objNum, _gostring_ message);
	Swig_DirectorCallback_callback_PartDownloadedProc_pdftron_5f1e8caadb3437e6(arg1,  dlType,  doc,  pageNum,  objNum,  message);

}


_gostring_ cgo_Swig_DirectorSignatureHandler_callback_GetName_pdftron_5f1e8caadb3437e6(uintptr_t arg1)
{
	_gostring_ Swig_DirectorSignatureHandler_callback_GetName_pdftron_5f1e8caadb3437e6(uintptr_t);
	return Swig_DirectorSignatureHandler_callback_GetName_pdftron_5f1e8caadb3437e6(arg1);

}
void cgo_Swig_DirectorSignatureHandler_callback_AppendData_pdftron_5f1e8caadb3437e6(uintptr_t arg1, uintptr_t data)
{
	void Swig_DirectorSignatureHandler_callback_AppendData_pdftron_5f1e8caadb3437e6(uintptr_t, uintptr_t data);
	Swig_DirectorSignatureHandler_callback_AppendData_pdftron_5f1e8caadb3437e6(arg1, data);
}
_Bool cgo_Swig_DirectorSignatureHandler_callback_Reset_pdftron_5f1e8caadb3437e6(uintptr_t arg1)
{
	_Bool Swig_DirectorSignatureHandler_callback_Reset_pdftron_5f1e8caadb3437e6(uintptr_t);
	return Swig_DirectorSignatureHandler_callback_Reset_pdftron_5f1e8caadb3437e6(arg1);

}
uintptr_t cgo_Swig_DirectorSignatureHandler_callback_CreateSignature_pdftron_5f1e8caadb3437e6(uintptr_t arg1)
{
	uintptr_t Swig_DirectorSignatureHandler_callback_CreateSignature_pdftron_5f1e8caadb3437e6(uintptr_t);
	return Swig_DirectorSignatureHandler_callback_CreateSignature_pdftron_5f1e8caadb3437e6(arg1);
}
uintptr_t cgo_Swig_DirectorSignatureHandler_callback_Clone_pdftron_5f1e8caadb3437e6(uintptr_t arg1)
{
	uintptr_t Swig_DirectorSignatureHandler_callback_Clone_pdftron_5f1e8caadb3437e6(uintptr_t arg1);
	return Swig_DirectorSignatureHandler_callback_Clone_pdftron_5f1e8caadb3437e6(arg1);
}
void cgo_Swiggo_DeleteDirector_SignatureHandler_pdftron_5f1e8caadb3437e6(uintptr_t arg1)
{
	void Swiggo_DeleteDirector_SignatureHandler_pdftron_5f1e8caadb3437e6(uintptr_t arg1);
	Swiggo_DeleteDirector_SignatureHandler_pdftron_5f1e8caadb3437e6(arg1);

}


*/
import "C"