//---------------------------------------------------------------------------------------
// Copyright (c) 2001-2021 by PDFTron Systems Inc. All Rights Reserved.
// Consult legal.txt regarding legal and license information.
//---------------------------------------------------------------------------------------
// !Warning! This file is autogenerated, modify the .codegen file, not this one
// (any changes here will be wiped out during the autogen process)

#ifndef PDFTRON_H_CBlackBoxContext
#define PDFTRON_H_CBlackBoxContext

#ifdef __cplusplus
extern "C" {
#endif

#include <C/Common/TRN_Types.h>
#include <C/Common/TRN_Exception.h>


struct TRN_BlackBoxContext_tag;
typedef struct TRN_BlackBoxContext_tag* TRN_BlackBoxContext;

/* enums:  */
enum TRN_BlackBoxContext_Result {
	e_BlackBoxContext_Success = 0,
	e_BlackBoxContext_Incomplete = 1,
	e_BlackBoxContext_Failure = 2
};

/* methods: */
TRN_API TRN_BlackBoxContextDoOperation(TRN_BlackBoxContext self, TRN_UString instructions, TRN_UString* result);
TRN_API TRN_BlackBoxContextGetDoc(TRN_BlackBoxContext self, TRN_PDFDoc* result);

TRN_API TRN_BlackBoxContextDestroy(TRN_BlackBoxContext* self);


#ifdef __cplusplus
} // extern C
#endif

#endif /* PDFTRON_H_CBlackBoxContext */
