//---------------------------------------------------------------------------------------
// Copyright (c) 2001-2021 by PDFTron Systems Inc. All Rights Reserved.
// Consult legal.txt regarding legal and license information.
//---------------------------------------------------------------------------------------
// !Warning! This file is autogenerated, modify the .codegen file, not this one
// (any changes here will be wiped out during the autogen process)

#ifndef PDFTRON_H_CPDF2HtmlReflowParagraphsModule
#define PDFTRON_H_CPDF2HtmlReflowParagraphsModule

#ifdef __cplusplus
extern "C" {
#endif

#include <C/Common/TRN_Types.h>
#include <C/Common/TRN_Exception.h>


struct TRN_PDF2HtmlReflowParagraphsModule_tag;
typedef struct TRN_PDF2HtmlReflowParagraphsModule_tag* TRN_PDF2HtmlReflowParagraphsModule;


/* methods: */
TRN_API TRN_PDF2HtmlReflowParagraphsModuleIsModuleAvailable(TRN_Bool* result);



#ifdef __cplusplus
} // extern C
#endif

#endif /* PDFTRON_H_CPDF2HtmlReflowParagraphsModule */
